ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS fee_fixed DECIMAL(20,2) NOT NULL DEFAULT 0;
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS fee_rate_amount DECIMAL(20,2) NOT NULL DEFAULT 0;
ALTER TABLE payment_orders ADD COLUMN IF NOT EXISTS fee_amount DECIMAL(20,2) NOT NULL DEFAULT 0;
