// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/apikey"
	"github.com/TokenFlux/TokenRouter/ent/apikeycompositegroup"
	"github.com/TokenFlux/TokenRouter/ent/group"
)

// APIKeyCompositeGroup is the model entity for the APIKeyCompositeGroup schema.
type APIKeyCompositeGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Prefix holds the value of the "prefix" field.
	Prefix string `json:"prefix,omitempty"`
	// NormalizedPrefix holds the value of the "normalized_prefix" field.
	NormalizedPrefix string `json:"normalized_prefix,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyCompositeGroupQuery when eager-loading is set.
	Edges        APIKeyCompositeGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyCompositeGroupEdges holds the relations/edges for other nodes in the graph.
type APIKeyCompositeGroupEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyCompositeGroupEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyCompositeGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyCompositeGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeycompositegroup.FieldID, apikeycompositegroup.FieldAPIKeyID, apikeycompositegroup.FieldGroupID, apikeycompositegroup.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case apikeycompositegroup.FieldPrefix, apikeycompositegroup.FieldNormalizedPrefix:
			values[i] = new(sql.NullString)
		case apikeycompositegroup.FieldCreatedAt, apikeycompositegroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyCompositeGroup fields.
func (_m *APIKeyCompositeGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeycompositegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case apikeycompositegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeycompositegroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeycompositegroup.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeycompositegroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case apikeycompositegroup.FieldPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prefix", values[i])
			} else if value.Valid {
				_m.Prefix = value.String
			}
		case apikeycompositegroup.FieldNormalizedPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_prefix", values[i])
			} else if value.Valid {
				_m.NormalizedPrefix = value.String
			}
		case apikeycompositegroup.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyCompositeGroup.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyCompositeGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the APIKeyCompositeGroup entity.
func (_m *APIKeyCompositeGroup) QueryAPIKey() *APIKeyQuery {
	return NewAPIKeyCompositeGroupClient(_m.config).QueryAPIKey(_m)
}

// QueryGroup queries the "group" edge of the APIKeyCompositeGroup entity.
func (_m *APIKeyCompositeGroup) QueryGroup() *GroupQuery {
	return NewAPIKeyCompositeGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this APIKeyCompositeGroup.
// Note that you need to call APIKeyCompositeGroup.Unwrap() before calling this method if this APIKeyCompositeGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyCompositeGroup) Update() *APIKeyCompositeGroupUpdateOne {
	return NewAPIKeyCompositeGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyCompositeGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyCompositeGroup) Unwrap() *APIKeyCompositeGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyCompositeGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyCompositeGroup) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyCompositeGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("prefix=")
	builder.WriteString(_m.Prefix)
	builder.WriteString(", ")
	builder.WriteString("normalized_prefix=")
	builder.WriteString(_m.NormalizedPrefix)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyCompositeGroups is a parsable slice of APIKeyCompositeGroup.
type APIKeyCompositeGroups []*APIKeyCompositeGroup
