// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/apikey"
	"github.com/TokenFlux/TokenRouter/ent/apikeycompositegroup"
	"github.com/TokenFlux/TokenRouter/ent/group"
)

// APIKeyCompositeGroupCreate is the builder for creating a APIKeyCompositeGroup entity.
type APIKeyCompositeGroupCreate struct {
	config
	mutation *APIKeyCompositeGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyCompositeGroupCreate) SetCreatedAt(v time.Time) *APIKeyCompositeGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyCompositeGroupCreate) SetNillableCreatedAt(v *time.Time) *APIKeyCompositeGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyCompositeGroupCreate) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyCompositeGroupCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyCompositeGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyCompositeGroupCreate) SetAPIKeyID(v int64) *APIKeyCompositeGroupCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *APIKeyCompositeGroupCreate) SetGroupID(v int64) *APIKeyCompositeGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *APIKeyCompositeGroupCreate) SetPrefix(v string) *APIKeyCompositeGroupCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (_c *APIKeyCompositeGroupCreate) SetNormalizedPrefix(v string) *APIKeyCompositeGroupCreate {
	_c.mutation.SetNormalizedPrefix(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *APIKeyCompositeGroupCreate) SetSortOrder(v int) *APIKeyCompositeGroupCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *APIKeyCompositeGroupCreate) SetNillableSortOrder(v *int) *APIKeyCompositeGroupCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyCompositeGroupCreate) SetAPIKey(v *APIKey) *APIKeyCompositeGroupCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *APIKeyCompositeGroupCreate) SetGroup(v *Group) *APIKeyCompositeGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the APIKeyCompositeGroupMutation object of the builder.
func (_c *APIKeyCompositeGroupCreate) Mutation() *APIKeyCompositeGroupMutation {
	return _c.mutation
}

// Save creates the APIKeyCompositeGroup in the database.
func (_c *APIKeyCompositeGroupCreate) Save(ctx context.Context) (*APIKeyCompositeGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyCompositeGroupCreate) SaveX(ctx context.Context) *APIKeyCompositeGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyCompositeGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyCompositeGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyCompositeGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeycompositegroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeycompositegroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := apikeycompositegroup.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyCompositeGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.group_id"`)}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := apikeycompositegroup.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedPrefix(); !ok {
		return &ValidationError{Name: "normalized_prefix", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.normalized_prefix"`)}
	}
	if v, ok := _c.mutation.NormalizedPrefix(); ok {
		if err := apikeycompositegroup.NormalizedPrefixValidator(v); err != nil {
			return &ValidationError{Name: "normalized_prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.normalized_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "APIKeyCompositeGroup.sort_order"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyCompositeGroup.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "APIKeyCompositeGroup.group"`)}
	}
	return nil
}

func (_c *APIKeyCompositeGroupCreate) sqlSave(ctx context.Context) (*APIKeyCompositeGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyCompositeGroupCreate) createSpec() (*APIKeyCompositeGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyCompositeGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeycompositegroup.Table, sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeycompositegroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeycompositegroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.NormalizedPrefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldNormalizedPrefix, field.TypeString, value)
		_node.NormalizedPrefix = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(apikeycompositegroup.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.APIKeyTable,
			Columns: []string{apikeycompositegroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.GroupTable,
			Columns: []string{apikeycompositegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyCompositeGroup.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyCompositeGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyCompositeGroupCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyCompositeGroupUpsertOne {
	_c.conflict = opts
	return &APIKeyCompositeGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyCompositeGroupCreate) OnConflictColumns(columns ...string) *APIKeyCompositeGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyCompositeGroupUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyCompositeGroupUpsertOne is the builder for "upsert"-ing
	//  one APIKeyCompositeGroup node.
	APIKeyCompositeGroupUpsertOne struct {
		create *APIKeyCompositeGroupCreate
	}

	// APIKeyCompositeGroupUpsert is the "OnConflict" setter.
	APIKeyCompositeGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyCompositeGroupUpsert) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdateUpdatedAt() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyCompositeGroupUpsert) SetAPIKeyID(v int64) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdateAPIKeyID() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyCompositeGroupUpsert) SetGroupID(v int64) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdateGroupID() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldGroupID)
	return u
}

// SetPrefix sets the "prefix" field.
func (u *APIKeyCompositeGroupUpsert) SetPrefix(v string) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldPrefix, v)
	return u
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdatePrefix() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldPrefix)
	return u
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (u *APIKeyCompositeGroupUpsert) SetNormalizedPrefix(v string) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldNormalizedPrefix, v)
	return u
}

// UpdateNormalizedPrefix sets the "normalized_prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdateNormalizedPrefix() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldNormalizedPrefix)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *APIKeyCompositeGroupUpsert) SetSortOrder(v int) *APIKeyCompositeGroupUpsert {
	u.Set(apikeycompositegroup.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsert) UpdateSortOrder() *APIKeyCompositeGroupUpsert {
	u.SetExcluded(apikeycompositegroup.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *APIKeyCompositeGroupUpsert) AddSortOrder(v int) *APIKeyCompositeGroupUpsert {
	u.Add(apikeycompositegroup.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyCompositeGroupUpsertOne) UpdateNewValues() *APIKeyCompositeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeycompositegroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyCompositeGroupUpsertOne) Ignore() *APIKeyCompositeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyCompositeGroupUpsertOne) DoNothing() *APIKeyCompositeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyCompositeGroupCreate.OnConflict
// documentation for more info.
func (u *APIKeyCompositeGroupUpsertOne) Update(set func(*APIKeyCompositeGroupUpsert)) *APIKeyCompositeGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyCompositeGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyCompositeGroupUpsertOne) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdateUpdatedAt() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyCompositeGroupUpsertOne) SetAPIKeyID(v int64) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdateAPIKeyID() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyCompositeGroupUpsertOne) SetGroupID(v int64) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdateGroupID() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrefix sets the "prefix" field.
func (u *APIKeyCompositeGroupUpsertOne) SetPrefix(v string) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdatePrefix() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdatePrefix()
	})
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (u *APIKeyCompositeGroupUpsertOne) SetNormalizedPrefix(v string) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetNormalizedPrefix(v)
	})
}

// UpdateNormalizedPrefix sets the "normalized_prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdateNormalizedPrefix() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateNormalizedPrefix()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *APIKeyCompositeGroupUpsertOne) SetSortOrder(v int) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *APIKeyCompositeGroupUpsertOne) AddSortOrder(v int) *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertOne) UpdateSortOrder() *APIKeyCompositeGroupUpsertOne {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *APIKeyCompositeGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyCompositeGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyCompositeGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyCompositeGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyCompositeGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyCompositeGroupCreateBulk is the builder for creating many APIKeyCompositeGroup entities in bulk.
type APIKeyCompositeGroupCreateBulk struct {
	config
	err      error
	builders []*APIKeyCompositeGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyCompositeGroup entities in the database.
func (_c *APIKeyCompositeGroupCreateBulk) Save(ctx context.Context) ([]*APIKeyCompositeGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyCompositeGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyCompositeGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyCompositeGroupCreateBulk) SaveX(ctx context.Context) []*APIKeyCompositeGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyCompositeGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyCompositeGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyCompositeGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyCompositeGroupUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyCompositeGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyCompositeGroupUpsertBulk {
	_c.conflict = opts
	return &APIKeyCompositeGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyCompositeGroupCreateBulk) OnConflictColumns(columns ...string) *APIKeyCompositeGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyCompositeGroupUpsertBulk{
		create: _c,
	}
}

// APIKeyCompositeGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyCompositeGroup nodes.
type APIKeyCompositeGroupUpsertBulk struct {
	create *APIKeyCompositeGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyCompositeGroupUpsertBulk) UpdateNewValues() *APIKeyCompositeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeycompositegroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyCompositeGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyCompositeGroupUpsertBulk) Ignore() *APIKeyCompositeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyCompositeGroupUpsertBulk) DoNothing() *APIKeyCompositeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyCompositeGroupCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyCompositeGroupUpsertBulk) Update(set func(*APIKeyCompositeGroupUpsert)) *APIKeyCompositeGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyCompositeGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdateUpdatedAt() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetAPIKeyID(v int64) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdateAPIKeyID() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetGroupID(v int64) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdateGroupID() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetPrefix sets the "prefix" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetPrefix(v string) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetPrefix(v)
	})
}

// UpdatePrefix sets the "prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdatePrefix() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdatePrefix()
	})
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetNormalizedPrefix(v string) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetNormalizedPrefix(v)
	})
}

// UpdateNormalizedPrefix sets the "normalized_prefix" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdateNormalizedPrefix() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateNormalizedPrefix()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *APIKeyCompositeGroupUpsertBulk) SetSortOrder(v int) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *APIKeyCompositeGroupUpsertBulk) AddSortOrder(v int) *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *APIKeyCompositeGroupUpsertBulk) UpdateSortOrder() *APIKeyCompositeGroupUpsertBulk {
	return u.Update(func(s *APIKeyCompositeGroupUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *APIKeyCompositeGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyCompositeGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyCompositeGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyCompositeGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
