// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/apikey"
	"github.com/TokenFlux/TokenRouter/ent/apikeycompositegroup"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// APIKeyCompositeGroupUpdate is the builder for updating APIKeyCompositeGroup entities.
type APIKeyCompositeGroupUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyCompositeGroupMutation
}

// Where appends a list predicates to the APIKeyCompositeGroupUpdate builder.
func (_u *APIKeyCompositeGroupUpdate) Where(ps ...predicate.APIKeyCompositeGroup) *APIKeyCompositeGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyCompositeGroupUpdate) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyCompositeGroupUpdate) SetAPIKeyID(v int64) *APIKeyCompositeGroupUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdate) SetNillableAPIKeyID(v *int64) *APIKeyCompositeGroupUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyCompositeGroupUpdate) SetGroupID(v int64) *APIKeyCompositeGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdate) SetNillableGroupID(v *int64) *APIKeyCompositeGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *APIKeyCompositeGroupUpdate) SetPrefix(v string) *APIKeyCompositeGroupUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdate) SetNillablePrefix(v *string) *APIKeyCompositeGroupUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (_u *APIKeyCompositeGroupUpdate) SetNormalizedPrefix(v string) *APIKeyCompositeGroupUpdate {
	_u.mutation.SetNormalizedPrefix(v)
	return _u
}

// SetNillableNormalizedPrefix sets the "normalized_prefix" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdate) SetNillableNormalizedPrefix(v *string) *APIKeyCompositeGroupUpdate {
	if v != nil {
		_u.SetNormalizedPrefix(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *APIKeyCompositeGroupUpdate) SetSortOrder(v int) *APIKeyCompositeGroupUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdate) SetNillableSortOrder(v *int) *APIKeyCompositeGroupUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *APIKeyCompositeGroupUpdate) AddSortOrder(v int) *APIKeyCompositeGroupUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyCompositeGroupUpdate) SetAPIKey(v *APIKey) *APIKeyCompositeGroupUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyCompositeGroupUpdate) SetGroup(v *Group) *APIKeyCompositeGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyCompositeGroupMutation object of the builder.
func (_u *APIKeyCompositeGroupUpdate) Mutation() *APIKeyCompositeGroupMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyCompositeGroupUpdate) ClearAPIKey() *APIKeyCompositeGroupUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyCompositeGroupUpdate) ClearGroup() *APIKeyCompositeGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyCompositeGroupUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyCompositeGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyCompositeGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyCompositeGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyCompositeGroupUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeycompositegroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyCompositeGroupUpdate) check() error {
	if v, ok := _u.mutation.Prefix(); ok {
		if err := apikeycompositegroup.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedPrefix(); ok {
		if err := apikeycompositegroup.NormalizedPrefixValidator(v); err != nil {
			return &ValidationError{Name: "normalized_prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.normalized_prefix": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyCompositeGroup.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyCompositeGroup.group"`)
	}
	return nil
}

func (_u *APIKeyCompositeGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeycompositegroup.Table, apikeycompositegroup.Columns, sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeycompositegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedPrefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldNormalizedPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(apikeycompositegroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(apikeycompositegroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.APIKeyTable,
			Columns: []string{apikeycompositegroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.APIKeyTable,
			Columns: []string{apikeycompositegroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.GroupTable,
			Columns: []string{apikeycompositegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.GroupTable,
			Columns: []string{apikeycompositegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeycompositegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyCompositeGroupUpdateOne is the builder for updating a single APIKeyCompositeGroup entity.
type APIKeyCompositeGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyCompositeGroupMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetUpdatedAt(v time.Time) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetAPIKeyID(v int64) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyCompositeGroupUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetGroupID(v int64) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdateOne) SetNillableGroupID(v *int64) *APIKeyCompositeGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetPrefix(v string) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdateOne) SetNillablePrefix(v *string) *APIKeyCompositeGroupUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetNormalizedPrefix sets the "normalized_prefix" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetNormalizedPrefix(v string) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.SetNormalizedPrefix(v)
	return _u
}

// SetNillableNormalizedPrefix sets the "normalized_prefix" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdateOne) SetNillableNormalizedPrefix(v *string) *APIKeyCompositeGroupUpdateOne {
	if v != nil {
		_u.SetNormalizedPrefix(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *APIKeyCompositeGroupUpdateOne) SetSortOrder(v int) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *APIKeyCompositeGroupUpdateOne) SetNillableSortOrder(v *int) *APIKeyCompositeGroupUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *APIKeyCompositeGroupUpdateOne) AddSortOrder(v int) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyCompositeGroupUpdateOne) SetAPIKey(v *APIKey) *APIKeyCompositeGroupUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *APIKeyCompositeGroupUpdateOne) SetGroup(v *Group) *APIKeyCompositeGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the APIKeyCompositeGroupMutation object of the builder.
func (_u *APIKeyCompositeGroupUpdateOne) Mutation() *APIKeyCompositeGroupMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyCompositeGroupUpdateOne) ClearAPIKey() *APIKeyCompositeGroupUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *APIKeyCompositeGroupUpdateOne) ClearGroup() *APIKeyCompositeGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the APIKeyCompositeGroupUpdate builder.
func (_u *APIKeyCompositeGroupUpdateOne) Where(ps ...predicate.APIKeyCompositeGroup) *APIKeyCompositeGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyCompositeGroupUpdateOne) Select(field string, fields ...string) *APIKeyCompositeGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyCompositeGroup entity.
func (_u *APIKeyCompositeGroupUpdateOne) Save(ctx context.Context) (*APIKeyCompositeGroup, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyCompositeGroupUpdateOne) SaveX(ctx context.Context) *APIKeyCompositeGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyCompositeGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyCompositeGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyCompositeGroupUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeycompositegroup.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyCompositeGroupUpdateOne) check() error {
	if v, ok := _u.mutation.Prefix(); ok {
		if err := apikeycompositegroup.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedPrefix(); ok {
		if err := apikeycompositegroup.NormalizedPrefixValidator(v); err != nil {
			return &ValidationError{Name: "normalized_prefix", err: fmt.Errorf(`ent: validator failed for field "APIKeyCompositeGroup.normalized_prefix": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyCompositeGroup.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyCompositeGroup.group"`)
	}
	return nil
}

func (_u *APIKeyCompositeGroupUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyCompositeGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeycompositegroup.Table, apikeycompositegroup.Columns, sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyCompositeGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeycompositegroup.FieldID)
		for _, f := range fields {
			if !apikeycompositegroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeycompositegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeycompositegroup.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedPrefix(); ok {
		_spec.SetField(apikeycompositegroup.FieldNormalizedPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(apikeycompositegroup.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(apikeycompositegroup.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.APIKeyTable,
			Columns: []string{apikeycompositegroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.APIKeyTable,
			Columns: []string{apikeycompositegroup.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.GroupTable,
			Columns: []string{apikeycompositegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeycompositegroup.GroupTable,
			Columns: []string{apikeycompositegroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKeyCompositeGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeycompositegroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
