// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/apikeycompositegroup"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// APIKeyCompositeGroupDelete is the builder for deleting a APIKeyCompositeGroup entity.
type APIKeyCompositeGroupDelete struct {
	config
	hooks    []Hook
	mutation *APIKeyCompositeGroupMutation
}

// Where appends a list predicates to the APIKeyCompositeGroupDelete builder.
func (_d *APIKeyCompositeGroupDelete) Where(ps ...predicate.APIKeyCompositeGroup) *APIKeyCompositeGroupDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *APIKeyCompositeGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyCompositeGroupDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *APIKeyCompositeGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeycompositegroup.Table, sqlgraph.NewFieldSpec(apikeycompositegroup.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// APIKeyCompositeGroupDeleteOne is the builder for deleting a single APIKeyCompositeGroup entity.
type APIKeyCompositeGroupDeleteOne struct {
	_d *APIKeyCompositeGroupDelete
}

// Where appends a list predicates to the APIKeyCompositeGroupDelete builder.
func (_d *APIKeyCompositeGroupDeleteOne) Where(ps ...predicate.APIKeyCompositeGroup) *APIKeyCompositeGroupDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *APIKeyCompositeGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeycompositegroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyCompositeGroupDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
