// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/creativerun"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/internal/domain"
)

// CreativeRunUpdate is the builder for updating CreativeRun entities.
type CreativeRunUpdate struct {
	config
	hooks    []Hook
	mutation *CreativeRunMutation
}

// Where appends a list predicates to the CreativeRunUpdate builder.
func (_u *CreativeRunUpdate) Where(ps ...predicate.CreativeRun) *CreativeRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreativeRunUpdate) SetUpdatedAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CreativeRunUpdate) SetUserID(v int64) *CreativeRunUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableUserID(v *int64) *CreativeRunUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreativeRunUpdate) AddUserID(v int64) *CreativeRunUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CreativeRunUpdate) SetWorkspaceID(v string) *CreativeRunUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableWorkspaceID(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *CreativeRunUpdate) ClearWorkspaceID() *CreativeRunUpdate {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CreativeRunUpdate) SetGroupID(v int64) *CreativeRunUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableGroupID(v *int64) *CreativeRunUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *CreativeRunUpdate) AddGroupID(v int64) *CreativeRunUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CreativeRunUpdate) SetAPIKeyID(v int64) *CreativeRunUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableAPIKeyID(v *int64) *CreativeRunUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *CreativeRunUpdate) AddAPIKeyID(v int64) *CreativeRunUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CreativeRunUpdate) SetAccountID(v int64) *CreativeRunUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableAccountID(v *int64) *CreativeRunUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *CreativeRunUpdate) AddAccountID(v int64) *CreativeRunUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CreativeRunUpdate) ClearAccountID() *CreativeRunUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetModel sets the "model" field.
func (_u *CreativeRunUpdate) SetModel(v string) *CreativeRunUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableModel(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *CreativeRunUpdate) SetRequestedModel(v string) *CreativeRunUpdate {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableRequestedModel(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *CreativeRunUpdate) SetOperation(v string) *CreativeRunUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableOperation(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetRequestedOutputCount sets the "requested_output_count" field.
func (_u *CreativeRunUpdate) SetRequestedOutputCount(v int) *CreativeRunUpdate {
	_u.mutation.ResetRequestedOutputCount()
	_u.mutation.SetRequestedOutputCount(v)
	return _u
}

// SetNillableRequestedOutputCount sets the "requested_output_count" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableRequestedOutputCount(v *int) *CreativeRunUpdate {
	if v != nil {
		_u.SetRequestedOutputCount(*v)
	}
	return _u
}

// AddRequestedOutputCount adds value to the "requested_output_count" field.
func (_u *CreativeRunUpdate) AddRequestedOutputCount(v int) *CreativeRunUpdate {
	_u.mutation.AddRequestedOutputCount(v)
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *CreativeRunUpdate) SetImageSize(v string) *CreativeRunUpdate {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableImageSize(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetAspectRatio sets the "aspect_ratio" field.
func (_u *CreativeRunUpdate) SetAspectRatio(v string) *CreativeRunUpdate {
	_u.mutation.SetAspectRatio(v)
	return _u
}

// SetNillableAspectRatio sets the "aspect_ratio" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableAspectRatio(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetAspectRatio(*v)
	}
	return _u
}

// SetResponseMimeType sets the "response_mime_type" field.
func (_u *CreativeRunUpdate) SetResponseMimeType(v string) *CreativeRunUpdate {
	_u.mutation.SetResponseMimeType(v)
	return _u
}

// SetNillableResponseMimeType sets the "response_mime_type" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableResponseMimeType(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetResponseMimeType(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *CreativeRunUpdate) SetPromptHash(v string) *CreativeRunUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillablePromptHash(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *CreativeRunUpdate) SetRequestFingerprint(v string) *CreativeRunUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableRequestFingerprint(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CreativeRunUpdate) SetIdempotencyKey(v string) *CreativeRunUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableIdempotencyKey(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *CreativeRunUpdate) ClearIdempotencyKey() *CreativeRunUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreativeRunUpdate) SetStatus(v string) *CreativeRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableStatus(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *CreativeRunUpdate) SetEstimatedCost(v float64) *CreativeRunUpdate {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableEstimatedCost(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *CreativeRunUpdate) AddEstimatedCost(v float64) *CreativeRunUpdate {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetHoldAmount sets the "hold_amount" field.
func (_u *CreativeRunUpdate) SetHoldAmount(v float64) *CreativeRunUpdate {
	_u.mutation.ResetHoldAmount()
	_u.mutation.SetHoldAmount(v)
	return _u
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableHoldAmount(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetHoldAmount(*v)
	}
	return _u
}

// AddHoldAmount adds value to the "hold_amount" field.
func (_u *CreativeRunUpdate) AddHoldAmount(v float64) *CreativeRunUpdate {
	_u.mutation.AddHoldAmount(v)
	return _u
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (_u *CreativeRunUpdate) ClearHoldAmount() *CreativeRunUpdate {
	_u.mutation.ClearHoldAmount()
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *CreativeRunUpdate) SetActualCost(v float64) *CreativeRunUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableActualCost(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *CreativeRunUpdate) AddActualCost(v float64) *CreativeRunUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *CreativeRunUpdate) ClearActualCost() *CreativeRunUpdate {
	_u.mutation.ClearActualCost()
	return _u
}

// SetBalanceHoldAmount sets the "balance_hold_amount" field.
func (_u *CreativeRunUpdate) SetBalanceHoldAmount(v float64) *CreativeRunUpdate {
	_u.mutation.ResetBalanceHoldAmount()
	_u.mutation.SetBalanceHoldAmount(v)
	return _u
}

// SetNillableBalanceHoldAmount sets the "balance_hold_amount" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableBalanceHoldAmount(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetBalanceHoldAmount(*v)
	}
	return _u
}

// AddBalanceHoldAmount adds value to the "balance_hold_amount" field.
func (_u *CreativeRunUpdate) AddBalanceHoldAmount(v float64) *CreativeRunUpdate {
	_u.mutation.AddBalanceHoldAmount(v)
	return _u
}

// SetSubscriptionHoldAllocations sets the "subscription_hold_allocations" field.
func (_u *CreativeRunUpdate) SetSubscriptionHoldAllocations(v []domain.BillingAllocation) *CreativeRunUpdate {
	_u.mutation.SetSubscriptionHoldAllocations(v)
	return _u
}

// AppendSubscriptionHoldAllocations appends value to the "subscription_hold_allocations" field.
func (_u *CreativeRunUpdate) AppendSubscriptionHoldAllocations(v []domain.BillingAllocation) *CreativeRunUpdate {
	_u.mutation.AppendSubscriptionHoldAllocations(v)
	return _u
}

// SetBaseUnitPrice sets the "base_unit_price" field.
func (_u *CreativeRunUpdate) SetBaseUnitPrice(v float64) *CreativeRunUpdate {
	_u.mutation.ResetBaseUnitPrice()
	_u.mutation.SetBaseUnitPrice(v)
	return _u
}

// SetNillableBaseUnitPrice sets the "base_unit_price" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableBaseUnitPrice(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetBaseUnitPrice(*v)
	}
	return _u
}

// AddBaseUnitPrice adds value to the "base_unit_price" field.
func (_u *CreativeRunUpdate) AddBaseUnitPrice(v float64) *CreativeRunUpdate {
	_u.mutation.AddBaseUnitPrice(v)
	return _u
}

// SetSubscriptionRateMultiplier sets the "subscription_rate_multiplier" field.
func (_u *CreativeRunUpdate) SetSubscriptionRateMultiplier(v float64) *CreativeRunUpdate {
	_u.mutation.ResetSubscriptionRateMultiplier()
	_u.mutation.SetSubscriptionRateMultiplier(v)
	return _u
}

// SetNillableSubscriptionRateMultiplier sets the "subscription_rate_multiplier" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableSubscriptionRateMultiplier(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetSubscriptionRateMultiplier(*v)
	}
	return _u
}

// AddSubscriptionRateMultiplier adds value to the "subscription_rate_multiplier" field.
func (_u *CreativeRunUpdate) AddSubscriptionRateMultiplier(v float64) *CreativeRunUpdate {
	_u.mutation.AddSubscriptionRateMultiplier(v)
	return _u
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (_u *CreativeRunUpdate) SetBalanceRateMultiplier(v float64) *CreativeRunUpdate {
	_u.mutation.ResetBalanceRateMultiplier()
	_u.mutation.SetBalanceRateMultiplier(v)
	return _u
}

// SetNillableBalanceRateMultiplier sets the "balance_rate_multiplier" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableBalanceRateMultiplier(v *float64) *CreativeRunUpdate {
	if v != nil {
		_u.SetBalanceRateMultiplier(*v)
	}
	return _u
}

// AddBalanceRateMultiplier adds value to the "balance_rate_multiplier" field.
func (_u *CreativeRunUpdate) AddBalanceRateMultiplier(v float64) *CreativeRunUpdate {
	_u.mutation.AddBalanceRateMultiplier(v)
	return _u
}

// SetPlanGroupRateMultiplierEnabled sets the "plan_group_rate_multiplier_enabled" field.
func (_u *CreativeRunUpdate) SetPlanGroupRateMultiplierEnabled(v bool) *CreativeRunUpdate {
	_u.mutation.SetPlanGroupRateMultiplierEnabled(v)
	return _u
}

// SetNillablePlanGroupRateMultiplierEnabled sets the "plan_group_rate_multiplier_enabled" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillablePlanGroupRateMultiplierEnabled(v *bool) *CreativeRunUpdate {
	if v != nil {
		_u.SetPlanGroupRateMultiplierEnabled(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CreativeRunUpdate) SetErrorCode(v string) *CreativeRunUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableErrorCode(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CreativeRunUpdate) ClearErrorCode() *CreativeRunUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CreativeRunUpdate) SetErrorMessage(v string) *CreativeRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableErrorMessage(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CreativeRunUpdate) ClearErrorMessage() *CreativeRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetReleaseTargetStatus sets the "release_target_status" field.
func (_u *CreativeRunUpdate) SetReleaseTargetStatus(v string) *CreativeRunUpdate {
	_u.mutation.SetReleaseTargetStatus(v)
	return _u
}

// SetNillableReleaseTargetStatus sets the "release_target_status" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableReleaseTargetStatus(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetReleaseTargetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *CreativeRunUpdate) SetAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableAttemptCount(v *int) *CreativeRunUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *CreativeRunUpdate) AddAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetAllowanceReserved sets the "allowance_reserved" field.
func (_u *CreativeRunUpdate) SetAllowanceReserved(v bool) *CreativeRunUpdate {
	_u.mutation.SetAllowanceReserved(v)
	return _u
}

// SetNillableAllowanceReserved sets the "allowance_reserved" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableAllowanceReserved(v *bool) *CreativeRunUpdate {
	if v != nil {
		_u.SetAllowanceReserved(*v)
	}
	return _u
}

// SetProvisioningPhase sets the "provisioning_phase" field.
func (_u *CreativeRunUpdate) SetProvisioningPhase(v string) *CreativeRunUpdate {
	_u.mutation.SetProvisioningPhase(v)
	return _u
}

// SetNillableProvisioningPhase sets the "provisioning_phase" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableProvisioningPhase(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetProvisioningPhase(*v)
	}
	return _u
}

// SetProviderResultRecordedAt sets the "provider_result_recorded_at" field.
func (_u *CreativeRunUpdate) SetProviderResultRecordedAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetProviderResultRecordedAt(v)
	return _u
}

// SetNillableProviderResultRecordedAt sets the "provider_result_recorded_at" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableProviderResultRecordedAt(v *time.Time) *CreativeRunUpdate {
	if v != nil {
		_u.SetProviderResultRecordedAt(*v)
	}
	return _u
}

// ClearProviderResultRecordedAt clears the value of the "provider_result_recorded_at" field.
func (_u *CreativeRunUpdate) ClearProviderResultRecordedAt() *CreativeRunUpdate {
	_u.mutation.ClearProviderResultRecordedAt()
	return _u
}

// SetSettlementAttemptCount sets the "settlement_attempt_count" field.
func (_u *CreativeRunUpdate) SetSettlementAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.ResetSettlementAttemptCount()
	_u.mutation.SetSettlementAttemptCount(v)
	return _u
}

// SetNillableSettlementAttemptCount sets the "settlement_attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableSettlementAttemptCount(v *int) *CreativeRunUpdate {
	if v != nil {
		_u.SetSettlementAttemptCount(*v)
	}
	return _u
}

// AddSettlementAttemptCount adds value to the "settlement_attempt_count" field.
func (_u *CreativeRunUpdate) AddSettlementAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.AddSettlementAttemptCount(v)
	return _u
}

// SetReleaseAttemptCount sets the "release_attempt_count" field.
func (_u *CreativeRunUpdate) SetReleaseAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.ResetReleaseAttemptCount()
	_u.mutation.SetReleaseAttemptCount(v)
	return _u
}

// SetNillableReleaseAttemptCount sets the "release_attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableReleaseAttemptCount(v *int) *CreativeRunUpdate {
	if v != nil {
		_u.SetReleaseAttemptCount(*v)
	}
	return _u
}

// AddReleaseAttemptCount adds value to the "release_attempt_count" field.
func (_u *CreativeRunUpdate) AddReleaseAttemptCount(v int) *CreativeRunUpdate {
	_u.mutation.AddReleaseAttemptCount(v)
	return _u
}

// SetNextReconcileAt sets the "next_reconcile_at" field.
func (_u *CreativeRunUpdate) SetNextReconcileAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetNextReconcileAt(v)
	return _u
}

// SetNillableNextReconcileAt sets the "next_reconcile_at" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableNextReconcileAt(v *time.Time) *CreativeRunUpdate {
	if v != nil {
		_u.SetNextReconcileAt(*v)
	}
	return _u
}

// ClearNextReconcileAt clears the value of the "next_reconcile_at" field.
func (_u *CreativeRunUpdate) ClearNextReconcileAt() *CreativeRunUpdate {
	_u.mutation.ClearNextReconcileAt()
	return _u
}

// SetLastReconcileError sets the "last_reconcile_error" field.
func (_u *CreativeRunUpdate) SetLastReconcileError(v string) *CreativeRunUpdate {
	_u.mutation.SetLastReconcileError(v)
	return _u
}

// SetNillableLastReconcileError sets the "last_reconcile_error" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableLastReconcileError(v *string) *CreativeRunUpdate {
	if v != nil {
		_u.SetLastReconcileError(*v)
	}
	return _u
}

// ClearLastReconcileError clears the value of the "last_reconcile_error" field.
func (_u *CreativeRunUpdate) ClearLastReconcileError() *CreativeRunUpdate {
	_u.mutation.ClearLastReconcileError()
	return _u
}

// SetVersion sets the "version" field.
func (_u *CreativeRunUpdate) SetVersion(v int64) *CreativeRunUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableVersion(v *int64) *CreativeRunUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CreativeRunUpdate) AddVersion(v int64) *CreativeRunUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CreativeRunUpdate) SetStartedAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableStartedAt(v *time.Time) *CreativeRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CreativeRunUpdate) ClearStartedAt() *CreativeRunUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CreativeRunUpdate) SetCompletedAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableCompletedAt(v *time.Time) *CreativeRunUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CreativeRunUpdate) ClearCompletedAt() *CreativeRunUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *CreativeRunUpdate) SetCancelledAt(v time.Time) *CreativeRunUpdate {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *CreativeRunUpdate) SetNillableCancelledAt(v *time.Time) *CreativeRunUpdate {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *CreativeRunUpdate) ClearCancelledAt() *CreativeRunUpdate {
	_u.mutation.ClearCancelledAt()
	return _u
}

// Mutation returns the CreativeRunMutation object of the builder.
func (_u *CreativeRunUpdate) Mutation() *CreativeRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreativeRunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreativeRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreativeRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreativeRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreativeRunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creativerun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreativeRunUpdate) check() error {
	if v, ok := _u.mutation.WorkspaceID(); ok {
		if err := creativerun.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.workspace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creativerun.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := creativerun.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := creativerun.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := creativerun.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AspectRatio(); ok {
		if err := creativerun.AspectRatioValidator(v); err != nil {
			return &ValidationError{Name: "aspect_ratio", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.aspect_ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMimeType(); ok {
		if err := creativerun.ResponseMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "response_mime_type", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.response_mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := creativerun.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := creativerun.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := creativerun.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creativerun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := creativerun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseTargetStatus(); ok {
		if err := creativerun.ReleaseTargetStatusValidator(v); err != nil {
			return &ValidationError{Name: "release_target_status", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.release_target_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProvisioningPhase(); ok {
		if err := creativerun.ProvisioningPhaseValidator(v); err != nil {
			return &ValidationError{Name: "provisioning_phase", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.provisioning_phase": %w`, err)}
		}
	}
	return nil
}

func (_u *CreativeRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creativerun.Table, creativerun.Columns, sqlgraph.NewFieldSpec(creativerun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creativerun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creativerun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creativerun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(creativerun.FieldWorkspaceID, field.TypeString, value)
	}
	if _u.mutation.WorkspaceIDCleared() {
		_spec.ClearField(creativerun.FieldWorkspaceID, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(creativerun.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(creativerun.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(creativerun.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(creativerun.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(creativerun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(creativerun.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(creativerun.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creativerun.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(creativerun.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(creativerun.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedOutputCount(); ok {
		_spec.SetField(creativerun.FieldRequestedOutputCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestedOutputCount(); ok {
		_spec.AddField(creativerun.FieldRequestedOutputCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(creativerun.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.AspectRatio(); ok {
		_spec.SetField(creativerun.FieldAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseMimeType(); ok {
		_spec.SetField(creativerun.FieldResponseMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(creativerun.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(creativerun.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(creativerun.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(creativerun.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creativerun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(creativerun.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(creativerun.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HoldAmount(); ok {
		_spec.SetField(creativerun.FieldHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoldAmount(); ok {
		_spec.AddField(creativerun.FieldHoldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.HoldAmountCleared() {
		_spec.ClearField(creativerun.FieldHoldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(creativerun.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(creativerun.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(creativerun.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceHoldAmount(); ok {
		_spec.SetField(creativerun.FieldBalanceHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceHoldAmount(); ok {
		_spec.AddField(creativerun.FieldBalanceHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubscriptionHoldAllocations(); ok {
		_spec.SetField(creativerun.FieldSubscriptionHoldAllocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSubscriptionHoldAllocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, creativerun.FieldSubscriptionHoldAllocations, value)
		})
	}
	if value, ok := _u.mutation.BaseUnitPrice(); ok {
		_spec.SetField(creativerun.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseUnitPrice(); ok {
		_spec.AddField(creativerun.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubscriptionRateMultiplier(); ok {
		_spec.SetField(creativerun.FieldSubscriptionRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionRateMultiplier(); ok {
		_spec.AddField(creativerun.FieldSubscriptionRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceRateMultiplier(); ok {
		_spec.SetField(creativerun.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceRateMultiplier(); ok {
		_spec.AddField(creativerun.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanGroupRateMultiplierEnabled(); ok {
		_spec.SetField(creativerun.FieldPlanGroupRateMultiplierEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(creativerun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(creativerun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(creativerun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(creativerun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseTargetStatus(); ok {
		_spec.SetField(creativerun.FieldReleaseTargetStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(creativerun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(creativerun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowanceReserved(); ok {
		_spec.SetField(creativerun.FieldAllowanceReserved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProvisioningPhase(); ok {
		_spec.SetField(creativerun.FieldProvisioningPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderResultRecordedAt(); ok {
		_spec.SetField(creativerun.FieldProviderResultRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.ProviderResultRecordedAtCleared() {
		_spec.ClearField(creativerun.FieldProviderResultRecordedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettlementAttemptCount(); ok {
		_spec.SetField(creativerun.FieldSettlementAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementAttemptCount(); ok {
		_spec.AddField(creativerun.FieldSettlementAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReleaseAttemptCount(); ok {
		_spec.SetField(creativerun.FieldReleaseAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseAttemptCount(); ok {
		_spec.AddField(creativerun.FieldReleaseAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextReconcileAt(); ok {
		_spec.SetField(creativerun.FieldNextReconcileAt, field.TypeTime, value)
	}
	if _u.mutation.NextReconcileAtCleared() {
		_spec.ClearField(creativerun.FieldNextReconcileAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReconcileError(); ok {
		_spec.SetField(creativerun.FieldLastReconcileError, field.TypeString, value)
	}
	if _u.mutation.LastReconcileErrorCleared() {
		_spec.ClearField(creativerun.FieldLastReconcileError, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(creativerun.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(creativerun.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(creativerun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(creativerun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(creativerun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(creativerun.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(creativerun.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(creativerun.FieldCancelledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creativerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreativeRunUpdateOne is the builder for updating a single CreativeRun entity.
type CreativeRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreativeRunMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreativeRunUpdateOne) SetUpdatedAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CreativeRunUpdateOne) SetUserID(v int64) *CreativeRunUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableUserID(v *int64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CreativeRunUpdateOne) AddUserID(v int64) *CreativeRunUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *CreativeRunUpdateOne) SetWorkspaceID(v string) *CreativeRunUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableWorkspaceID(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *CreativeRunUpdateOne) ClearWorkspaceID() *CreativeRunUpdateOne {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CreativeRunUpdateOne) SetGroupID(v int64) *CreativeRunUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableGroupID(v *int64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *CreativeRunUpdateOne) AddGroupID(v int64) *CreativeRunUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *CreativeRunUpdateOne) SetAPIKeyID(v int64) *CreativeRunUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableAPIKeyID(v *int64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *CreativeRunUpdateOne) AddAPIKeyID(v int64) *CreativeRunUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CreativeRunUpdateOne) SetAccountID(v int64) *CreativeRunUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableAccountID(v *int64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *CreativeRunUpdateOne) AddAccountID(v int64) *CreativeRunUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *CreativeRunUpdateOne) ClearAccountID() *CreativeRunUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetModel sets the "model" field.
func (_u *CreativeRunUpdateOne) SetModel(v string) *CreativeRunUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableModel(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *CreativeRunUpdateOne) SetRequestedModel(v string) *CreativeRunUpdateOne {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableRequestedModel(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *CreativeRunUpdateOne) SetOperation(v string) *CreativeRunUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableOperation(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetRequestedOutputCount sets the "requested_output_count" field.
func (_u *CreativeRunUpdateOne) SetRequestedOutputCount(v int) *CreativeRunUpdateOne {
	_u.mutation.ResetRequestedOutputCount()
	_u.mutation.SetRequestedOutputCount(v)
	return _u
}

// SetNillableRequestedOutputCount sets the "requested_output_count" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableRequestedOutputCount(v *int) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetRequestedOutputCount(*v)
	}
	return _u
}

// AddRequestedOutputCount adds value to the "requested_output_count" field.
func (_u *CreativeRunUpdateOne) AddRequestedOutputCount(v int) *CreativeRunUpdateOne {
	_u.mutation.AddRequestedOutputCount(v)
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *CreativeRunUpdateOne) SetImageSize(v string) *CreativeRunUpdateOne {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableImageSize(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// SetAspectRatio sets the "aspect_ratio" field.
func (_u *CreativeRunUpdateOne) SetAspectRatio(v string) *CreativeRunUpdateOne {
	_u.mutation.SetAspectRatio(v)
	return _u
}

// SetNillableAspectRatio sets the "aspect_ratio" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableAspectRatio(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetAspectRatio(*v)
	}
	return _u
}

// SetResponseMimeType sets the "response_mime_type" field.
func (_u *CreativeRunUpdateOne) SetResponseMimeType(v string) *CreativeRunUpdateOne {
	_u.mutation.SetResponseMimeType(v)
	return _u
}

// SetNillableResponseMimeType sets the "response_mime_type" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableResponseMimeType(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetResponseMimeType(*v)
	}
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *CreativeRunUpdateOne) SetPromptHash(v string) *CreativeRunUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillablePromptHash(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *CreativeRunUpdateOne) SetRequestFingerprint(v string) *CreativeRunUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableRequestFingerprint(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *CreativeRunUpdateOne) SetIdempotencyKey(v string) *CreativeRunUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableIdempotencyKey(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *CreativeRunUpdateOne) ClearIdempotencyKey() *CreativeRunUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreativeRunUpdateOne) SetStatus(v string) *CreativeRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableStatus(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *CreativeRunUpdateOne) SetEstimatedCost(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableEstimatedCost(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *CreativeRunUpdateOne) AddEstimatedCost(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetHoldAmount sets the "hold_amount" field.
func (_u *CreativeRunUpdateOne) SetHoldAmount(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetHoldAmount()
	_u.mutation.SetHoldAmount(v)
	return _u
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableHoldAmount(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetHoldAmount(*v)
	}
	return _u
}

// AddHoldAmount adds value to the "hold_amount" field.
func (_u *CreativeRunUpdateOne) AddHoldAmount(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddHoldAmount(v)
	return _u
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (_u *CreativeRunUpdateOne) ClearHoldAmount() *CreativeRunUpdateOne {
	_u.mutation.ClearHoldAmount()
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *CreativeRunUpdateOne) SetActualCost(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableActualCost(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *CreativeRunUpdateOne) AddActualCost(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *CreativeRunUpdateOne) ClearActualCost() *CreativeRunUpdateOne {
	_u.mutation.ClearActualCost()
	return _u
}

// SetBalanceHoldAmount sets the "balance_hold_amount" field.
func (_u *CreativeRunUpdateOne) SetBalanceHoldAmount(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetBalanceHoldAmount()
	_u.mutation.SetBalanceHoldAmount(v)
	return _u
}

// SetNillableBalanceHoldAmount sets the "balance_hold_amount" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableBalanceHoldAmount(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetBalanceHoldAmount(*v)
	}
	return _u
}

// AddBalanceHoldAmount adds value to the "balance_hold_amount" field.
func (_u *CreativeRunUpdateOne) AddBalanceHoldAmount(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddBalanceHoldAmount(v)
	return _u
}

// SetSubscriptionHoldAllocations sets the "subscription_hold_allocations" field.
func (_u *CreativeRunUpdateOne) SetSubscriptionHoldAllocations(v []domain.BillingAllocation) *CreativeRunUpdateOne {
	_u.mutation.SetSubscriptionHoldAllocations(v)
	return _u
}

// AppendSubscriptionHoldAllocations appends value to the "subscription_hold_allocations" field.
func (_u *CreativeRunUpdateOne) AppendSubscriptionHoldAllocations(v []domain.BillingAllocation) *CreativeRunUpdateOne {
	_u.mutation.AppendSubscriptionHoldAllocations(v)
	return _u
}

// SetBaseUnitPrice sets the "base_unit_price" field.
func (_u *CreativeRunUpdateOne) SetBaseUnitPrice(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetBaseUnitPrice()
	_u.mutation.SetBaseUnitPrice(v)
	return _u
}

// SetNillableBaseUnitPrice sets the "base_unit_price" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableBaseUnitPrice(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetBaseUnitPrice(*v)
	}
	return _u
}

// AddBaseUnitPrice adds value to the "base_unit_price" field.
func (_u *CreativeRunUpdateOne) AddBaseUnitPrice(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddBaseUnitPrice(v)
	return _u
}

// SetSubscriptionRateMultiplier sets the "subscription_rate_multiplier" field.
func (_u *CreativeRunUpdateOne) SetSubscriptionRateMultiplier(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetSubscriptionRateMultiplier()
	_u.mutation.SetSubscriptionRateMultiplier(v)
	return _u
}

// SetNillableSubscriptionRateMultiplier sets the "subscription_rate_multiplier" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableSubscriptionRateMultiplier(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetSubscriptionRateMultiplier(*v)
	}
	return _u
}

// AddSubscriptionRateMultiplier adds value to the "subscription_rate_multiplier" field.
func (_u *CreativeRunUpdateOne) AddSubscriptionRateMultiplier(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddSubscriptionRateMultiplier(v)
	return _u
}

// SetBalanceRateMultiplier sets the "balance_rate_multiplier" field.
func (_u *CreativeRunUpdateOne) SetBalanceRateMultiplier(v float64) *CreativeRunUpdateOne {
	_u.mutation.ResetBalanceRateMultiplier()
	_u.mutation.SetBalanceRateMultiplier(v)
	return _u
}

// SetNillableBalanceRateMultiplier sets the "balance_rate_multiplier" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableBalanceRateMultiplier(v *float64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetBalanceRateMultiplier(*v)
	}
	return _u
}

// AddBalanceRateMultiplier adds value to the "balance_rate_multiplier" field.
func (_u *CreativeRunUpdateOne) AddBalanceRateMultiplier(v float64) *CreativeRunUpdateOne {
	_u.mutation.AddBalanceRateMultiplier(v)
	return _u
}

// SetPlanGroupRateMultiplierEnabled sets the "plan_group_rate_multiplier_enabled" field.
func (_u *CreativeRunUpdateOne) SetPlanGroupRateMultiplierEnabled(v bool) *CreativeRunUpdateOne {
	_u.mutation.SetPlanGroupRateMultiplierEnabled(v)
	return _u
}

// SetNillablePlanGroupRateMultiplierEnabled sets the "plan_group_rate_multiplier_enabled" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillablePlanGroupRateMultiplierEnabled(v *bool) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetPlanGroupRateMultiplierEnabled(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CreativeRunUpdateOne) SetErrorCode(v string) *CreativeRunUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableErrorCode(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CreativeRunUpdateOne) ClearErrorCode() *CreativeRunUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CreativeRunUpdateOne) SetErrorMessage(v string) *CreativeRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableErrorMessage(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CreativeRunUpdateOne) ClearErrorMessage() *CreativeRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetReleaseTargetStatus sets the "release_target_status" field.
func (_u *CreativeRunUpdateOne) SetReleaseTargetStatus(v string) *CreativeRunUpdateOne {
	_u.mutation.SetReleaseTargetStatus(v)
	return _u
}

// SetNillableReleaseTargetStatus sets the "release_target_status" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableReleaseTargetStatus(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetReleaseTargetStatus(*v)
	}
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *CreativeRunUpdateOne) SetAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableAttemptCount(v *int) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *CreativeRunUpdateOne) AddAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetAllowanceReserved sets the "allowance_reserved" field.
func (_u *CreativeRunUpdateOne) SetAllowanceReserved(v bool) *CreativeRunUpdateOne {
	_u.mutation.SetAllowanceReserved(v)
	return _u
}

// SetNillableAllowanceReserved sets the "allowance_reserved" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableAllowanceReserved(v *bool) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetAllowanceReserved(*v)
	}
	return _u
}

// SetProvisioningPhase sets the "provisioning_phase" field.
func (_u *CreativeRunUpdateOne) SetProvisioningPhase(v string) *CreativeRunUpdateOne {
	_u.mutation.SetProvisioningPhase(v)
	return _u
}

// SetNillableProvisioningPhase sets the "provisioning_phase" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableProvisioningPhase(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetProvisioningPhase(*v)
	}
	return _u
}

// SetProviderResultRecordedAt sets the "provider_result_recorded_at" field.
func (_u *CreativeRunUpdateOne) SetProviderResultRecordedAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetProviderResultRecordedAt(v)
	return _u
}

// SetNillableProviderResultRecordedAt sets the "provider_result_recorded_at" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableProviderResultRecordedAt(v *time.Time) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetProviderResultRecordedAt(*v)
	}
	return _u
}

// ClearProviderResultRecordedAt clears the value of the "provider_result_recorded_at" field.
func (_u *CreativeRunUpdateOne) ClearProviderResultRecordedAt() *CreativeRunUpdateOne {
	_u.mutation.ClearProviderResultRecordedAt()
	return _u
}

// SetSettlementAttemptCount sets the "settlement_attempt_count" field.
func (_u *CreativeRunUpdateOne) SetSettlementAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.ResetSettlementAttemptCount()
	_u.mutation.SetSettlementAttemptCount(v)
	return _u
}

// SetNillableSettlementAttemptCount sets the "settlement_attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableSettlementAttemptCount(v *int) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetSettlementAttemptCount(*v)
	}
	return _u
}

// AddSettlementAttemptCount adds value to the "settlement_attempt_count" field.
func (_u *CreativeRunUpdateOne) AddSettlementAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.AddSettlementAttemptCount(v)
	return _u
}

// SetReleaseAttemptCount sets the "release_attempt_count" field.
func (_u *CreativeRunUpdateOne) SetReleaseAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.ResetReleaseAttemptCount()
	_u.mutation.SetReleaseAttemptCount(v)
	return _u
}

// SetNillableReleaseAttemptCount sets the "release_attempt_count" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableReleaseAttemptCount(v *int) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetReleaseAttemptCount(*v)
	}
	return _u
}

// AddReleaseAttemptCount adds value to the "release_attempt_count" field.
func (_u *CreativeRunUpdateOne) AddReleaseAttemptCount(v int) *CreativeRunUpdateOne {
	_u.mutation.AddReleaseAttemptCount(v)
	return _u
}

// SetNextReconcileAt sets the "next_reconcile_at" field.
func (_u *CreativeRunUpdateOne) SetNextReconcileAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetNextReconcileAt(v)
	return _u
}

// SetNillableNextReconcileAt sets the "next_reconcile_at" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableNextReconcileAt(v *time.Time) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetNextReconcileAt(*v)
	}
	return _u
}

// ClearNextReconcileAt clears the value of the "next_reconcile_at" field.
func (_u *CreativeRunUpdateOne) ClearNextReconcileAt() *CreativeRunUpdateOne {
	_u.mutation.ClearNextReconcileAt()
	return _u
}

// SetLastReconcileError sets the "last_reconcile_error" field.
func (_u *CreativeRunUpdateOne) SetLastReconcileError(v string) *CreativeRunUpdateOne {
	_u.mutation.SetLastReconcileError(v)
	return _u
}

// SetNillableLastReconcileError sets the "last_reconcile_error" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableLastReconcileError(v *string) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetLastReconcileError(*v)
	}
	return _u
}

// ClearLastReconcileError clears the value of the "last_reconcile_error" field.
func (_u *CreativeRunUpdateOne) ClearLastReconcileError() *CreativeRunUpdateOne {
	_u.mutation.ClearLastReconcileError()
	return _u
}

// SetVersion sets the "version" field.
func (_u *CreativeRunUpdateOne) SetVersion(v int64) *CreativeRunUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableVersion(v *int64) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *CreativeRunUpdateOne) AddVersion(v int64) *CreativeRunUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *CreativeRunUpdateOne) SetStartedAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableStartedAt(v *time.Time) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *CreativeRunUpdateOne) ClearStartedAt() *CreativeRunUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CreativeRunUpdateOne) SetCompletedAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableCompletedAt(v *time.Time) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *CreativeRunUpdateOne) ClearCompletedAt() *CreativeRunUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *CreativeRunUpdateOne) SetCancelledAt(v time.Time) *CreativeRunUpdateOne {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *CreativeRunUpdateOne) SetNillableCancelledAt(v *time.Time) *CreativeRunUpdateOne {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *CreativeRunUpdateOne) ClearCancelledAt() *CreativeRunUpdateOne {
	_u.mutation.ClearCancelledAt()
	return _u
}

// Mutation returns the CreativeRunMutation object of the builder.
func (_u *CreativeRunUpdateOne) Mutation() *CreativeRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the CreativeRunUpdate builder.
func (_u *CreativeRunUpdateOne) Where(ps ...predicate.CreativeRun) *CreativeRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreativeRunUpdateOne) Select(field string, fields ...string) *CreativeRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreativeRun entity.
func (_u *CreativeRunUpdateOne) Save(ctx context.Context) (*CreativeRun, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreativeRunUpdateOne) SaveX(ctx context.Context) *CreativeRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreativeRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreativeRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreativeRunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creativerun.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreativeRunUpdateOne) check() error {
	if v, ok := _u.mutation.WorkspaceID(); ok {
		if err := creativerun.WorkspaceIDValidator(v); err != nil {
			return &ValidationError{Name: "workspace_id", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.workspace_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := creativerun.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := creativerun.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := creativerun.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := creativerun.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AspectRatio(); ok {
		if err := creativerun.AspectRatioValidator(v); err != nil {
			return &ValidationError{Name: "aspect_ratio", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.aspect_ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseMimeType(); ok {
		if err := creativerun.ResponseMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "response_mime_type", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.response_mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := creativerun.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := creativerun.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := creativerun.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creativerun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := creativerun.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseTargetStatus(); ok {
		if err := creativerun.ReleaseTargetStatusValidator(v); err != nil {
			return &ValidationError{Name: "release_target_status", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.release_target_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProvisioningPhase(); ok {
		if err := creativerun.ProvisioningPhaseValidator(v); err != nil {
			return &ValidationError{Name: "provisioning_phase", err: fmt.Errorf(`ent: validator failed for field "CreativeRun.provisioning_phase": %w`, err)}
		}
	}
	return nil
}

func (_u *CreativeRunUpdateOne) sqlSave(ctx context.Context) (_node *CreativeRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creativerun.Table, creativerun.Columns, sqlgraph.NewFieldSpec(creativerun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreativeRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creativerun.FieldID)
		for _, f := range fields {
			if !creativerun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creativerun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creativerun.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(creativerun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(creativerun.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkspaceID(); ok {
		_spec.SetField(creativerun.FieldWorkspaceID, field.TypeString, value)
	}
	if _u.mutation.WorkspaceIDCleared() {
		_spec.ClearField(creativerun.FieldWorkspaceID, field.TypeString)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(creativerun.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(creativerun.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(creativerun.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(creativerun.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(creativerun.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(creativerun.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(creativerun.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(creativerun.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(creativerun.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(creativerun.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedOutputCount(); ok {
		_spec.SetField(creativerun.FieldRequestedOutputCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestedOutputCount(); ok {
		_spec.AddField(creativerun.FieldRequestedOutputCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(creativerun.FieldImageSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.AspectRatio(); ok {
		_spec.SetField(creativerun.FieldAspectRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResponseMimeType(); ok {
		_spec.SetField(creativerun.FieldResponseMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(creativerun.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(creativerun.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(creativerun.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(creativerun.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creativerun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(creativerun.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(creativerun.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HoldAmount(); ok {
		_spec.SetField(creativerun.FieldHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoldAmount(); ok {
		_spec.AddField(creativerun.FieldHoldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.HoldAmountCleared() {
		_spec.ClearField(creativerun.FieldHoldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(creativerun.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(creativerun.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(creativerun.FieldActualCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceHoldAmount(); ok {
		_spec.SetField(creativerun.FieldBalanceHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceHoldAmount(); ok {
		_spec.AddField(creativerun.FieldBalanceHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubscriptionHoldAllocations(); ok {
		_spec.SetField(creativerun.FieldSubscriptionHoldAllocations, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSubscriptionHoldAllocations(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, creativerun.FieldSubscriptionHoldAllocations, value)
		})
	}
	if value, ok := _u.mutation.BaseUnitPrice(); ok {
		_spec.SetField(creativerun.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseUnitPrice(); ok {
		_spec.AddField(creativerun.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SubscriptionRateMultiplier(); ok {
		_spec.SetField(creativerun.FieldSubscriptionRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionRateMultiplier(); ok {
		_spec.AddField(creativerun.FieldSubscriptionRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceRateMultiplier(); ok {
		_spec.SetField(creativerun.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceRateMultiplier(); ok {
		_spec.AddField(creativerun.FieldBalanceRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PlanGroupRateMultiplierEnabled(); ok {
		_spec.SetField(creativerun.FieldPlanGroupRateMultiplierEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(creativerun.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(creativerun.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(creativerun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(creativerun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseTargetStatus(); ok {
		_spec.SetField(creativerun.FieldReleaseTargetStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(creativerun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(creativerun.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowanceReserved(); ok {
		_spec.SetField(creativerun.FieldAllowanceReserved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProvisioningPhase(); ok {
		_spec.SetField(creativerun.FieldProvisioningPhase, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderResultRecordedAt(); ok {
		_spec.SetField(creativerun.FieldProviderResultRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.ProviderResultRecordedAtCleared() {
		_spec.ClearField(creativerun.FieldProviderResultRecordedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettlementAttemptCount(); ok {
		_spec.SetField(creativerun.FieldSettlementAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementAttemptCount(); ok {
		_spec.AddField(creativerun.FieldSettlementAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReleaseAttemptCount(); ok {
		_spec.SetField(creativerun.FieldReleaseAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReleaseAttemptCount(); ok {
		_spec.AddField(creativerun.FieldReleaseAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextReconcileAt(); ok {
		_spec.SetField(creativerun.FieldNextReconcileAt, field.TypeTime, value)
	}
	if _u.mutation.NextReconcileAtCleared() {
		_spec.ClearField(creativerun.FieldNextReconcileAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReconcileError(); ok {
		_spec.SetField(creativerun.FieldLastReconcileError, field.TypeString, value)
	}
	if _u.mutation.LastReconcileErrorCleared() {
		_spec.ClearField(creativerun.FieldLastReconcileError, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(creativerun.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(creativerun.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(creativerun.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(creativerun.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(creativerun.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(creativerun.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(creativerun.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(creativerun.FieldCancelledAt, field.TypeTime)
	}
	_node = &CreativeRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creativerun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
