// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/creativerunoutput"
)

// CreativeRunOutput is the model entity for the CreativeRunOutput schema.
type CreativeRunOutput struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// OutputIndex holds the value of the "output_index" field.
	OutputIndex int `json:"output_index,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType *string `json:"mime_type,omitempty"`
	// ByteSize holds the value of the "byte_size" field.
	ByteSize *int64 `json:"byte_size,omitempty"`
	// TransientExpiresAt holds the value of the "transient_expires_at" field.
	TransientExpiresAt *time.Time `json:"transient_expires_at,omitempty"`
	// AckedAt holds the value of the "acked_at" field.
	AckedAt *time.Time `json:"acked_at,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreativeRunOutput) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creativerunoutput.FieldID, creativerunoutput.FieldOutputIndex, creativerunoutput.FieldByteSize:
			values[i] = new(sql.NullInt64)
		case creativerunoutput.FieldRunID, creativerunoutput.FieldStatus, creativerunoutput.FieldMimeType, creativerunoutput.FieldErrorCode, creativerunoutput.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case creativerunoutput.FieldCreatedAt, creativerunoutput.FieldUpdatedAt, creativerunoutput.FieldTransientExpiresAt, creativerunoutput.FieldAckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreativeRunOutput fields.
func (_m *CreativeRunOutput) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creativerunoutput.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creativerunoutput.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case creativerunoutput.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case creativerunoutput.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case creativerunoutput.FieldOutputIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_index", values[i])
			} else if value.Valid {
				_m.OutputIndex = int(value.Int64)
			}
		case creativerunoutput.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case creativerunoutput.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = new(string)
				*_m.MimeType = value.String
			}
		case creativerunoutput.FieldByteSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field byte_size", values[i])
			} else if value.Valid {
				_m.ByteSize = new(int64)
				*_m.ByteSize = value.Int64
			}
		case creativerunoutput.FieldTransientExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field transient_expires_at", values[i])
			} else if value.Valid {
				_m.TransientExpiresAt = new(time.Time)
				*_m.TransientExpiresAt = value.Time
			}
		case creativerunoutput.FieldAckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acked_at", values[i])
			} else if value.Valid {
				_m.AckedAt = new(time.Time)
				*_m.AckedAt = value.Time
			}
		case creativerunoutput.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case creativerunoutput.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreativeRunOutput.
// This includes values selected through modifiers, order, etc.
func (_m *CreativeRunOutput) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreativeRunOutput.
// Note that you need to call CreativeRunOutput.Unwrap() before calling this method if this CreativeRunOutput
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreativeRunOutput) Update() *CreativeRunOutputUpdateOne {
	return NewCreativeRunOutputClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreativeRunOutput entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreativeRunOutput) Unwrap() *CreativeRunOutput {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreativeRunOutput is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreativeRunOutput) String() string {
	var builder strings.Builder
	builder.WriteString("CreativeRunOutput(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("output_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputIndex))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.MimeType; v != nil {
		builder.WriteString("mime_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ByteSize; v != nil {
		builder.WriteString("byte_size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TransientExpiresAt; v != nil {
		builder.WriteString("transient_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AckedAt; v != nil {
		builder.WriteString("acked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CreativeRunOutputs is a parsable slice of CreativeRunOutput.
type CreativeRunOutputs []*CreativeRunOutput
