// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/creativerun"
	"github.com/TokenFlux/TokenRouter/internal/domain"
)

// CreativeRun is the model entity for the CreativeRun schema.
type CreativeRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID *string `json:"workspace_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// RequestedOutputCount holds the value of the "requested_output_count" field.
	RequestedOutputCount int `json:"requested_output_count,omitempty"`
	// ImageSize holds the value of the "image_size" field.
	ImageSize string `json:"image_size,omitempty"`
	// AspectRatio holds the value of the "aspect_ratio" field.
	AspectRatio string `json:"aspect_ratio,omitempty"`
	// ResponseMimeType holds the value of the "response_mime_type" field.
	ResponseMimeType string `json:"response_mime_type,omitempty"`
	// PromptHash holds the value of the "prompt_hash" field.
	PromptHash string `json:"prompt_hash,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// HoldAmount holds the value of the "hold_amount" field.
	HoldAmount *float64 `json:"hold_amount,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost *float64 `json:"actual_cost,omitempty"`
	// BalanceHoldAmount holds the value of the "balance_hold_amount" field.
	BalanceHoldAmount float64 `json:"balance_hold_amount,omitempty"`
	// SubscriptionHoldAllocations holds the value of the "subscription_hold_allocations" field.
	SubscriptionHoldAllocations []domain.BillingAllocation `json:"subscription_hold_allocations,omitempty"`
	// BaseUnitPrice holds the value of the "base_unit_price" field.
	BaseUnitPrice float64 `json:"base_unit_price,omitempty"`
	// SubscriptionRateMultiplier holds the value of the "subscription_rate_multiplier" field.
	SubscriptionRateMultiplier float64 `json:"subscription_rate_multiplier,omitempty"`
	// BalanceRateMultiplier holds the value of the "balance_rate_multiplier" field.
	BalanceRateMultiplier float64 `json:"balance_rate_multiplier,omitempty"`
	// PlanGroupRateMultiplierEnabled holds the value of the "plan_group_rate_multiplier_enabled" field.
	PlanGroupRateMultiplierEnabled bool `json:"plan_group_rate_multiplier_enabled,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ReleaseTargetStatus holds the value of the "release_target_status" field.
	ReleaseTargetStatus string `json:"release_target_status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// AllowanceReserved holds the value of the "allowance_reserved" field.
	AllowanceReserved bool `json:"allowance_reserved,omitempty"`
	// ProvisioningPhase holds the value of the "provisioning_phase" field.
	ProvisioningPhase string `json:"provisioning_phase,omitempty"`
	// ProviderResultRecordedAt holds the value of the "provider_result_recorded_at" field.
	ProviderResultRecordedAt *time.Time `json:"provider_result_recorded_at,omitempty"`
	// SettlementAttemptCount holds the value of the "settlement_attempt_count" field.
	SettlementAttemptCount int `json:"settlement_attempt_count,omitempty"`
	// ReleaseAttemptCount holds the value of the "release_attempt_count" field.
	ReleaseAttemptCount int `json:"release_attempt_count,omitempty"`
	// NextReconcileAt holds the value of the "next_reconcile_at" field.
	NextReconcileAt *time.Time `json:"next_reconcile_at,omitempty"`
	// LastReconcileError holds the value of the "last_reconcile_error" field.
	LastReconcileError *string `json:"last_reconcile_error,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt  *time.Time `json:"cancelled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CreativeRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case creativerun.FieldSubscriptionHoldAllocations:
			values[i] = new([]byte)
		case creativerun.FieldPlanGroupRateMultiplierEnabled, creativerun.FieldAllowanceReserved:
			values[i] = new(sql.NullBool)
		case creativerun.FieldEstimatedCost, creativerun.FieldHoldAmount, creativerun.FieldActualCost, creativerun.FieldBalanceHoldAmount, creativerun.FieldBaseUnitPrice, creativerun.FieldSubscriptionRateMultiplier, creativerun.FieldBalanceRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case creativerun.FieldID, creativerun.FieldUserID, creativerun.FieldGroupID, creativerun.FieldAPIKeyID, creativerun.FieldAccountID, creativerun.FieldRequestedOutputCount, creativerun.FieldAttemptCount, creativerun.FieldSettlementAttemptCount, creativerun.FieldReleaseAttemptCount, creativerun.FieldVersion:
			values[i] = new(sql.NullInt64)
		case creativerun.FieldRunID, creativerun.FieldWorkspaceID, creativerun.FieldModel, creativerun.FieldRequestedModel, creativerun.FieldOperation, creativerun.FieldImageSize, creativerun.FieldAspectRatio, creativerun.FieldResponseMimeType, creativerun.FieldPromptHash, creativerun.FieldRequestFingerprint, creativerun.FieldIdempotencyKey, creativerun.FieldStatus, creativerun.FieldErrorCode, creativerun.FieldErrorMessage, creativerun.FieldReleaseTargetStatus, creativerun.FieldProvisioningPhase, creativerun.FieldLastReconcileError:
			values[i] = new(sql.NullString)
		case creativerun.FieldCreatedAt, creativerun.FieldUpdatedAt, creativerun.FieldProviderResultRecordedAt, creativerun.FieldNextReconcileAt, creativerun.FieldStartedAt, creativerun.FieldCompletedAt, creativerun.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CreativeRun fields.
func (_m *CreativeRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creativerun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case creativerun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case creativerun.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case creativerun.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case creativerun.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case creativerun.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = new(string)
				*_m.WorkspaceID = value.String
			}
		case creativerun.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case creativerun.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case creativerun.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case creativerun.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case creativerun.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case creativerun.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case creativerun.FieldRequestedOutputCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_output_count", values[i])
			} else if value.Valid {
				_m.RequestedOutputCount = int(value.Int64)
			}
		case creativerun.FieldImageSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size", values[i])
			} else if value.Valid {
				_m.ImageSize = value.String
			}
		case creativerun.FieldAspectRatio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aspect_ratio", values[i])
			} else if value.Valid {
				_m.AspectRatio = value.String
			}
		case creativerun.FieldResponseMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_mime_type", values[i])
			} else if value.Valid {
				_m.ResponseMimeType = value.String
			}
		case creativerun.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = value.String
			}
		case creativerun.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case creativerun.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case creativerun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case creativerun.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case creativerun.FieldHoldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hold_amount", values[i])
			} else if value.Valid {
				_m.HoldAmount = new(float64)
				*_m.HoldAmount = value.Float64
			}
		case creativerun.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = new(float64)
				*_m.ActualCost = value.Float64
			}
		case creativerun.FieldBalanceHoldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_hold_amount", values[i])
			} else if value.Valid {
				_m.BalanceHoldAmount = value.Float64
			}
		case creativerun.FieldSubscriptionHoldAllocations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_hold_allocations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SubscriptionHoldAllocations); err != nil {
					return fmt.Errorf("unmarshal field subscription_hold_allocations: %w", err)
				}
			}
		case creativerun.FieldBaseUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_unit_price", values[i])
			} else if value.Valid {
				_m.BaseUnitPrice = value.Float64
			}
		case creativerun.FieldSubscriptionRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_rate_multiplier", values[i])
			} else if value.Valid {
				_m.SubscriptionRateMultiplier = value.Float64
			}
		case creativerun.FieldBalanceRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_rate_multiplier", values[i])
			} else if value.Valid {
				_m.BalanceRateMultiplier = value.Float64
			}
		case creativerun.FieldPlanGroupRateMultiplierEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field plan_group_rate_multiplier_enabled", values[i])
			} else if value.Valid {
				_m.PlanGroupRateMultiplierEnabled = value.Bool
			}
		case creativerun.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case creativerun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case creativerun.FieldReleaseTargetStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_target_status", values[i])
			} else if value.Valid {
				_m.ReleaseTargetStatus = value.String
			}
		case creativerun.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case creativerun.FieldAllowanceReserved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allowance_reserved", values[i])
			} else if value.Valid {
				_m.AllowanceReserved = value.Bool
			}
		case creativerun.FieldProvisioningPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provisioning_phase", values[i])
			} else if value.Valid {
				_m.ProvisioningPhase = value.String
			}
		case creativerun.FieldProviderResultRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field provider_result_recorded_at", values[i])
			} else if value.Valid {
				_m.ProviderResultRecordedAt = new(time.Time)
				*_m.ProviderResultRecordedAt = value.Time
			}
		case creativerun.FieldSettlementAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_attempt_count", values[i])
			} else if value.Valid {
				_m.SettlementAttemptCount = int(value.Int64)
			}
		case creativerun.FieldReleaseAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field release_attempt_count", values[i])
			} else if value.Valid {
				_m.ReleaseAttemptCount = int(value.Int64)
			}
		case creativerun.FieldNextReconcileAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_reconcile_at", values[i])
			} else if value.Valid {
				_m.NextReconcileAt = new(time.Time)
				*_m.NextReconcileAt = value.Time
			}
		case creativerun.FieldLastReconcileError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_reconcile_error", values[i])
			} else if value.Valid {
				_m.LastReconcileError = new(string)
				*_m.LastReconcileError = value.String
			}
		case creativerun.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case creativerun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case creativerun.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case creativerun.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CreativeRun.
// This includes values selected through modifiers, order, etc.
func (_m *CreativeRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CreativeRun.
// Note that you need to call CreativeRun.Unwrap() before calling this method if this CreativeRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CreativeRun) Update() *CreativeRunUpdateOne {
	return NewCreativeRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CreativeRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CreativeRun) Unwrap() *CreativeRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CreativeRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CreativeRun) String() string {
	var builder strings.Builder
	builder.WriteString("CreativeRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.WorkspaceID; v != nil {
		builder.WriteString("workspace_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("requested_output_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedOutputCount))
	builder.WriteString(", ")
	builder.WriteString("image_size=")
	builder.WriteString(_m.ImageSize)
	builder.WriteString(", ")
	builder.WriteString("aspect_ratio=")
	builder.WriteString(_m.AspectRatio)
	builder.WriteString(", ")
	builder.WriteString("response_mime_type=")
	builder.WriteString(_m.ResponseMimeType)
	builder.WriteString(", ")
	builder.WriteString("prompt_hash=")
	builder.WriteString(_m.PromptHash)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	if v := _m.HoldAmount; v != nil {
		builder.WriteString("hold_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualCost; v != nil {
		builder.WriteString("actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("balance_hold_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceHoldAmount))
	builder.WriteString(", ")
	builder.WriteString("subscription_hold_allocations=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionHoldAllocations))
	builder.WriteString(", ")
	builder.WriteString("base_unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseUnitPrice))
	builder.WriteString(", ")
	builder.WriteString("subscription_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("balance_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("plan_group_rate_multiplier_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanGroupRateMultiplierEnabled))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("release_target_status=")
	builder.WriteString(_m.ReleaseTargetStatus)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("allowance_reserved=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowanceReserved))
	builder.WriteString(", ")
	builder.WriteString("provisioning_phase=")
	builder.WriteString(_m.ProvisioningPhase)
	builder.WriteString(", ")
	if v := _m.ProviderResultRecordedAt; v != nil {
		builder.WriteString("provider_result_recorded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("settlement_attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementAttemptCount))
	builder.WriteString(", ")
	builder.WriteString("release_attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReleaseAttemptCount))
	builder.WriteString(", ")
	if v := _m.NextReconcileAt; v != nil {
		builder.WriteString("next_reconcile_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastReconcileError; v != nil {
		builder.WriteString("last_reconcile_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CreativeRuns is a parsable slice of CreativeRun.
type CreativeRuns []*CreativeRun
