// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/creativerunoutput"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// CreativeRunOutputUpdate is the builder for updating CreativeRunOutput entities.
type CreativeRunOutputUpdate struct {
	config
	hooks    []Hook
	mutation *CreativeRunOutputMutation
}

// Where appends a list predicates to the CreativeRunOutputUpdate builder.
func (_u *CreativeRunOutputUpdate) Where(ps ...predicate.CreativeRunOutput) *CreativeRunOutputUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreativeRunOutputUpdate) SetUpdatedAt(v time.Time) *CreativeRunOutputUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *CreativeRunOutputUpdate) SetRunID(v string) *CreativeRunOutputUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableRunID(v *string) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetOutputIndex sets the "output_index" field.
func (_u *CreativeRunOutputUpdate) SetOutputIndex(v int) *CreativeRunOutputUpdate {
	_u.mutation.ResetOutputIndex()
	_u.mutation.SetOutputIndex(v)
	return _u
}

// SetNillableOutputIndex sets the "output_index" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableOutputIndex(v *int) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetOutputIndex(*v)
	}
	return _u
}

// AddOutputIndex adds value to the "output_index" field.
func (_u *CreativeRunOutputUpdate) AddOutputIndex(v int) *CreativeRunOutputUpdate {
	_u.mutation.AddOutputIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreativeRunOutputUpdate) SetStatus(v string) *CreativeRunOutputUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableStatus(v *string) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *CreativeRunOutputUpdate) SetMimeType(v string) *CreativeRunOutputUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableMimeType(v *string) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *CreativeRunOutputUpdate) ClearMimeType() *CreativeRunOutputUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *CreativeRunOutputUpdate) SetByteSize(v int64) *CreativeRunOutputUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableByteSize(v *int64) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *CreativeRunOutputUpdate) AddByteSize(v int64) *CreativeRunOutputUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// ClearByteSize clears the value of the "byte_size" field.
func (_u *CreativeRunOutputUpdate) ClearByteSize() *CreativeRunOutputUpdate {
	_u.mutation.ClearByteSize()
	return _u
}

// SetTransientExpiresAt sets the "transient_expires_at" field.
func (_u *CreativeRunOutputUpdate) SetTransientExpiresAt(v time.Time) *CreativeRunOutputUpdate {
	_u.mutation.SetTransientExpiresAt(v)
	return _u
}

// SetNillableTransientExpiresAt sets the "transient_expires_at" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableTransientExpiresAt(v *time.Time) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetTransientExpiresAt(*v)
	}
	return _u
}

// ClearTransientExpiresAt clears the value of the "transient_expires_at" field.
func (_u *CreativeRunOutputUpdate) ClearTransientExpiresAt() *CreativeRunOutputUpdate {
	_u.mutation.ClearTransientExpiresAt()
	return _u
}

// SetAckedAt sets the "acked_at" field.
func (_u *CreativeRunOutputUpdate) SetAckedAt(v time.Time) *CreativeRunOutputUpdate {
	_u.mutation.SetAckedAt(v)
	return _u
}

// SetNillableAckedAt sets the "acked_at" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableAckedAt(v *time.Time) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetAckedAt(*v)
	}
	return _u
}

// ClearAckedAt clears the value of the "acked_at" field.
func (_u *CreativeRunOutputUpdate) ClearAckedAt() *CreativeRunOutputUpdate {
	_u.mutation.ClearAckedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CreativeRunOutputUpdate) SetErrorCode(v string) *CreativeRunOutputUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableErrorCode(v *string) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CreativeRunOutputUpdate) ClearErrorCode() *CreativeRunOutputUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CreativeRunOutputUpdate) SetErrorMessage(v string) *CreativeRunOutputUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CreativeRunOutputUpdate) SetNillableErrorMessage(v *string) *CreativeRunOutputUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CreativeRunOutputUpdate) ClearErrorMessage() *CreativeRunOutputUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the CreativeRunOutputMutation object of the builder.
func (_u *CreativeRunOutputUpdate) Mutation() *CreativeRunOutputMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CreativeRunOutputUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreativeRunOutputUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CreativeRunOutputUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreativeRunOutputUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreativeRunOutputUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creativerunoutput.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreativeRunOutputUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := creativerunoutput.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creativerunoutput.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := creativerunoutput.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := creativerunoutput.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *CreativeRunOutputUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creativerunoutput.Table, creativerunoutput.Columns, sqlgraph.NewFieldSpec(creativerunoutput.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creativerunoutput.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(creativerunoutput.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputIndex(); ok {
		_spec.SetField(creativerunoutput.FieldOutputIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputIndex(); ok {
		_spec.AddField(creativerunoutput.FieldOutputIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creativerunoutput.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(creativerunoutput.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(creativerunoutput.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(creativerunoutput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(creativerunoutput.FieldByteSize, field.TypeInt64, value)
	}
	if _u.mutation.ByteSizeCleared() {
		_spec.ClearField(creativerunoutput.FieldByteSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.TransientExpiresAt(); ok {
		_spec.SetField(creativerunoutput.FieldTransientExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TransientExpiresAtCleared() {
		_spec.ClearField(creativerunoutput.FieldTransientExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AckedAt(); ok {
		_spec.SetField(creativerunoutput.FieldAckedAt, field.TypeTime, value)
	}
	if _u.mutation.AckedAtCleared() {
		_spec.ClearField(creativerunoutput.FieldAckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(creativerunoutput.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(creativerunoutput.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(creativerunoutput.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(creativerunoutput.FieldErrorMessage, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creativerunoutput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CreativeRunOutputUpdateOne is the builder for updating a single CreativeRunOutput entity.
type CreativeRunOutputUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreativeRunOutputMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CreativeRunOutputUpdateOne) SetUpdatedAt(v time.Time) *CreativeRunOutputUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *CreativeRunOutputUpdateOne) SetRunID(v string) *CreativeRunOutputUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableRunID(v *string) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetOutputIndex sets the "output_index" field.
func (_u *CreativeRunOutputUpdateOne) SetOutputIndex(v int) *CreativeRunOutputUpdateOne {
	_u.mutation.ResetOutputIndex()
	_u.mutation.SetOutputIndex(v)
	return _u
}

// SetNillableOutputIndex sets the "output_index" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableOutputIndex(v *int) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetOutputIndex(*v)
	}
	return _u
}

// AddOutputIndex adds value to the "output_index" field.
func (_u *CreativeRunOutputUpdateOne) AddOutputIndex(v int) *CreativeRunOutputUpdateOne {
	_u.mutation.AddOutputIndex(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CreativeRunOutputUpdateOne) SetStatus(v string) *CreativeRunOutputUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableStatus(v *string) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *CreativeRunOutputUpdateOne) SetMimeType(v string) *CreativeRunOutputUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableMimeType(v *string) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *CreativeRunOutputUpdateOne) ClearMimeType() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *CreativeRunOutputUpdateOne) SetByteSize(v int64) *CreativeRunOutputUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableByteSize(v *int64) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *CreativeRunOutputUpdateOne) AddByteSize(v int64) *CreativeRunOutputUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// ClearByteSize clears the value of the "byte_size" field.
func (_u *CreativeRunOutputUpdateOne) ClearByteSize() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearByteSize()
	return _u
}

// SetTransientExpiresAt sets the "transient_expires_at" field.
func (_u *CreativeRunOutputUpdateOne) SetTransientExpiresAt(v time.Time) *CreativeRunOutputUpdateOne {
	_u.mutation.SetTransientExpiresAt(v)
	return _u
}

// SetNillableTransientExpiresAt sets the "transient_expires_at" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableTransientExpiresAt(v *time.Time) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetTransientExpiresAt(*v)
	}
	return _u
}

// ClearTransientExpiresAt clears the value of the "transient_expires_at" field.
func (_u *CreativeRunOutputUpdateOne) ClearTransientExpiresAt() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearTransientExpiresAt()
	return _u
}

// SetAckedAt sets the "acked_at" field.
func (_u *CreativeRunOutputUpdateOne) SetAckedAt(v time.Time) *CreativeRunOutputUpdateOne {
	_u.mutation.SetAckedAt(v)
	return _u
}

// SetNillableAckedAt sets the "acked_at" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableAckedAt(v *time.Time) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetAckedAt(*v)
	}
	return _u
}

// ClearAckedAt clears the value of the "acked_at" field.
func (_u *CreativeRunOutputUpdateOne) ClearAckedAt() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearAckedAt()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *CreativeRunOutputUpdateOne) SetErrorCode(v string) *CreativeRunOutputUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableErrorCode(v *string) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *CreativeRunOutputUpdateOne) ClearErrorCode() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *CreativeRunOutputUpdateOne) SetErrorMessage(v string) *CreativeRunOutputUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *CreativeRunOutputUpdateOne) SetNillableErrorMessage(v *string) *CreativeRunOutputUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *CreativeRunOutputUpdateOne) ClearErrorMessage() *CreativeRunOutputUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// Mutation returns the CreativeRunOutputMutation object of the builder.
func (_u *CreativeRunOutputUpdateOne) Mutation() *CreativeRunOutputMutation {
	return _u.mutation
}

// Where appends a list predicates to the CreativeRunOutputUpdate builder.
func (_u *CreativeRunOutputUpdateOne) Where(ps ...predicate.CreativeRunOutput) *CreativeRunOutputUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CreativeRunOutputUpdateOne) Select(field string, fields ...string) *CreativeRunOutputUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CreativeRunOutput entity.
func (_u *CreativeRunOutputUpdateOne) Save(ctx context.Context) (*CreativeRunOutput, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CreativeRunOutputUpdateOne) SaveX(ctx context.Context) *CreativeRunOutput {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CreativeRunOutputUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CreativeRunOutputUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CreativeRunOutputUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := creativerunoutput.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CreativeRunOutputUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := creativerunoutput.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := creativerunoutput.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := creativerunoutput.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := creativerunoutput.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "CreativeRunOutput.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *CreativeRunOutputUpdateOne) sqlSave(ctx context.Context) (_node *CreativeRunOutput, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(creativerunoutput.Table, creativerunoutput.Columns, sqlgraph.NewFieldSpec(creativerunoutput.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreativeRunOutput.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, creativerunoutput.FieldID)
		for _, f := range fields {
			if !creativerunoutput.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != creativerunoutput.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(creativerunoutput.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(creativerunoutput.FieldRunID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputIndex(); ok {
		_spec.SetField(creativerunoutput.FieldOutputIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputIndex(); ok {
		_spec.AddField(creativerunoutput.FieldOutputIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(creativerunoutput.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(creativerunoutput.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(creativerunoutput.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(creativerunoutput.FieldByteSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(creativerunoutput.FieldByteSize, field.TypeInt64, value)
	}
	if _u.mutation.ByteSizeCleared() {
		_spec.ClearField(creativerunoutput.FieldByteSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.TransientExpiresAt(); ok {
		_spec.SetField(creativerunoutput.FieldTransientExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TransientExpiresAtCleared() {
		_spec.ClearField(creativerunoutput.FieldTransientExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AckedAt(); ok {
		_spec.SetField(creativerunoutput.FieldAckedAt, field.TypeTime, value)
	}
	if _u.mutation.AckedAtCleared() {
		_spec.ClearField(creativerunoutput.FieldAckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(creativerunoutput.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(creativerunoutput.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(creativerunoutput.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(creativerunoutput.FieldErrorMessage, field.TypeString)
	}
	_node = &CreativeRunOutput{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{creativerunoutput.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
