// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/creativerunoutput"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// CreativeRunOutputDelete is the builder for deleting a CreativeRunOutput entity.
type CreativeRunOutputDelete struct {
	config
	hooks    []Hook
	mutation *CreativeRunOutputMutation
}

// Where appends a list predicates to the CreativeRunOutputDelete builder.
func (_d *CreativeRunOutputDelete) Where(ps ...predicate.CreativeRunOutput) *CreativeRunOutputDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CreativeRunOutputDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreativeRunOutputDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CreativeRunOutputDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(creativerunoutput.Table, sqlgraph.NewFieldSpec(creativerunoutput.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CreativeRunOutputDeleteOne is the builder for deleting a single CreativeRunOutput entity.
type CreativeRunOutputDeleteOne struct {
	_d *CreativeRunOutputDelete
}

// Where appends a list predicates to the CreativeRunOutputDelete builder.
func (_d *CreativeRunOutputDeleteOne) Where(ps ...predicate.CreativeRunOutput) *CreativeRunOutputDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CreativeRunOutputDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{creativerunoutput.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CreativeRunOutputDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
