// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/TokenFlux/TokenRouter/ent/group"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
	"github.com/TokenFlux/TokenRouter/ent/user"
	"github.com/TokenFlux/TokenRouter/ent/userdisabledpublicgroup"
)

// UserDisabledPublicGroupUpdate is the builder for updating UserDisabledPublicGroup entities.
type UserDisabledPublicGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserDisabledPublicGroupMutation
}

// Where appends a list predicates to the UserDisabledPublicGroupUpdate builder.
func (_u *UserDisabledPublicGroupUpdate) Where(ps ...predicate.UserDisabledPublicGroup) *UserDisabledPublicGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserDisabledPublicGroupUpdate) SetUserID(v int64) *UserDisabledPublicGroupUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDisabledPublicGroupUpdate) SetNillableUserID(v *int64) *UserDisabledPublicGroupUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserDisabledPublicGroupUpdate) SetGroupID(v int64) *UserDisabledPublicGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserDisabledPublicGroupUpdate) SetNillableGroupID(v *int64) *UserDisabledPublicGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserDisabledPublicGroupUpdate) SetUser(v *User) *UserDisabledPublicGroupUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserDisabledPublicGroupUpdate) SetGroup(v *Group) *UserDisabledPublicGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserDisabledPublicGroupMutation object of the builder.
func (_u *UserDisabledPublicGroupUpdate) Mutation() *UserDisabledPublicGroupMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserDisabledPublicGroupUpdate) ClearUser() *UserDisabledPublicGroupUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserDisabledPublicGroupUpdate) ClearGroup() *UserDisabledPublicGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserDisabledPublicGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDisabledPublicGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserDisabledPublicGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDisabledPublicGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDisabledPublicGroupUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDisabledPublicGroup.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDisabledPublicGroup.group"`)
	}
	return nil
}

func (_u *UserDisabledPublicGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdisabledpublicgroup.Table, userdisabledpublicgroup.Columns, sqlgraph.NewFieldSpec(userdisabledpublicgroup.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userdisabledpublicgroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.UserTable,
			Columns: []string{userdisabledpublicgroup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.UserTable,
			Columns: []string{userdisabledpublicgroup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.GroupTable,
			Columns: []string{userdisabledpublicgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.GroupTable,
			Columns: []string{userdisabledpublicgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdisabledpublicgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserDisabledPublicGroupUpdateOne is the builder for updating a single UserDisabledPublicGroup entity.
type UserDisabledPublicGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserDisabledPublicGroupMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserDisabledPublicGroupUpdateOne) SetUserID(v int64) *UserDisabledPublicGroupUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDisabledPublicGroupUpdateOne) SetNillableUserID(v *int64) *UserDisabledPublicGroupUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserDisabledPublicGroupUpdateOne) SetGroupID(v int64) *UserDisabledPublicGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserDisabledPublicGroupUpdateOne) SetNillableGroupID(v *int64) *UserDisabledPublicGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserDisabledPublicGroupUpdateOne) SetUser(v *User) *UserDisabledPublicGroupUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserDisabledPublicGroupUpdateOne) SetGroup(v *Group) *UserDisabledPublicGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserDisabledPublicGroupMutation object of the builder.
func (_u *UserDisabledPublicGroupUpdateOne) Mutation() *UserDisabledPublicGroupMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserDisabledPublicGroupUpdateOne) ClearUser() *UserDisabledPublicGroupUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserDisabledPublicGroupUpdateOne) ClearGroup() *UserDisabledPublicGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the UserDisabledPublicGroupUpdate builder.
func (_u *UserDisabledPublicGroupUpdateOne) Where(ps ...predicate.UserDisabledPublicGroup) *UserDisabledPublicGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserDisabledPublicGroupUpdateOne) Select(field string, fields ...string) *UserDisabledPublicGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserDisabledPublicGroup entity.
func (_u *UserDisabledPublicGroupUpdateOne) Save(ctx context.Context) (*UserDisabledPublicGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDisabledPublicGroupUpdateOne) SaveX(ctx context.Context) *UserDisabledPublicGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserDisabledPublicGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDisabledPublicGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDisabledPublicGroupUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDisabledPublicGroup.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDisabledPublicGroup.group"`)
	}
	return nil
}

func (_u *UserDisabledPublicGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserDisabledPublicGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdisabledpublicgroup.Table, userdisabledpublicgroup.Columns, sqlgraph.NewFieldSpec(userdisabledpublicgroup.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userdisabledpublicgroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "UserDisabledPublicGroup.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "UserDisabledPublicGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !userdisabledpublicgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.UserTable,
			Columns: []string{userdisabledpublicgroup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.UserTable,
			Columns: []string{userdisabledpublicgroup.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.GroupTable,
			Columns: []string{userdisabledpublicgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userdisabledpublicgroup.GroupTable,
			Columns: []string{userdisabledpublicgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserDisabledPublicGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdisabledpublicgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
