// Code generated by ent, DO NOT EDIT.

package creativerun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/internal/domain"
)

const (
	// Label holds the string label denoting the creativerun type in the database.
	Label = "creative_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldRequestedOutputCount holds the string denoting the requested_output_count field in the database.
	FieldRequestedOutputCount = "requested_output_count"
	// FieldImageSize holds the string denoting the image_size field in the database.
	FieldImageSize = "image_size"
	// FieldAspectRatio holds the string denoting the aspect_ratio field in the database.
	FieldAspectRatio = "aspect_ratio"
	// FieldResponseMimeType holds the string denoting the response_mime_type field in the database.
	FieldResponseMimeType = "response_mime_type"
	// FieldPromptHash holds the string denoting the prompt_hash field in the database.
	FieldPromptHash = "prompt_hash"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldBalanceHoldAmount holds the string denoting the balance_hold_amount field in the database.
	FieldBalanceHoldAmount = "balance_hold_amount"
	// FieldSubscriptionHoldAllocations holds the string denoting the subscription_hold_allocations field in the database.
	FieldSubscriptionHoldAllocations = "subscription_hold_allocations"
	// FieldBaseUnitPrice holds the string denoting the base_unit_price field in the database.
	FieldBaseUnitPrice = "base_unit_price"
	// FieldSubscriptionRateMultiplier holds the string denoting the subscription_rate_multiplier field in the database.
	FieldSubscriptionRateMultiplier = "subscription_rate_multiplier"
	// FieldBalanceRateMultiplier holds the string denoting the balance_rate_multiplier field in the database.
	FieldBalanceRateMultiplier = "balance_rate_multiplier"
	// FieldPlanGroupRateMultiplierEnabled holds the string denoting the plan_group_rate_multiplier_enabled field in the database.
	FieldPlanGroupRateMultiplierEnabled = "plan_group_rate_multiplier_enabled"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldReleaseTargetStatus holds the string denoting the release_target_status field in the database.
	FieldReleaseTargetStatus = "release_target_status"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldAllowanceReserved holds the string denoting the allowance_reserved field in the database.
	FieldAllowanceReserved = "allowance_reserved"
	// FieldProvisioningPhase holds the string denoting the provisioning_phase field in the database.
	FieldProvisioningPhase = "provisioning_phase"
	// FieldProviderResultRecordedAt holds the string denoting the provider_result_recorded_at field in the database.
	FieldProviderResultRecordedAt = "provider_result_recorded_at"
	// FieldSettlementAttemptCount holds the string denoting the settlement_attempt_count field in the database.
	FieldSettlementAttemptCount = "settlement_attempt_count"
	// FieldReleaseAttemptCount holds the string denoting the release_attempt_count field in the database.
	FieldReleaseAttemptCount = "release_attempt_count"
	// FieldNextReconcileAt holds the string denoting the next_reconcile_at field in the database.
	FieldNextReconcileAt = "next_reconcile_at"
	// FieldLastReconcileError holds the string denoting the last_reconcile_error field in the database.
	FieldLastReconcileError = "last_reconcile_error"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCancelledAt holds the string denoting the cancelled_at field in the database.
	FieldCancelledAt = "cancelled_at"
	// Table holds the table name of the creativerun in the database.
	Table = "creative_runs"
)

// Columns holds all SQL columns for creativerun fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRunID,
	FieldUserID,
	FieldWorkspaceID,
	FieldGroupID,
	FieldAPIKeyID,
	FieldAccountID,
	FieldModel,
	FieldRequestedModel,
	FieldOperation,
	FieldRequestedOutputCount,
	FieldImageSize,
	FieldAspectRatio,
	FieldResponseMimeType,
	FieldPromptHash,
	FieldRequestFingerprint,
	FieldIdempotencyKey,
	FieldStatus,
	FieldEstimatedCost,
	FieldHoldAmount,
	FieldActualCost,
	FieldBalanceHoldAmount,
	FieldSubscriptionHoldAllocations,
	FieldBaseUnitPrice,
	FieldSubscriptionRateMultiplier,
	FieldBalanceRateMultiplier,
	FieldPlanGroupRateMultiplierEnabled,
	FieldErrorCode,
	FieldErrorMessage,
	FieldReleaseTargetStatus,
	FieldAttemptCount,
	FieldAllowanceReserved,
	FieldProvisioningPhase,
	FieldProviderResultRecordedAt,
	FieldSettlementAttemptCount,
	FieldReleaseAttemptCount,
	FieldNextReconcileAt,
	FieldLastReconcileError,
	FieldVersion,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCancelledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	RunIDValidator func(string) error
	// WorkspaceIDValidator is a validator for the "workspace_id" field. It is called by the builders before save.
	WorkspaceIDValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultRequestedModel holds the default value on creation for the "requested_model" field.
	DefaultRequestedModel string
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// DefaultRequestedOutputCount holds the default value on creation for the "requested_output_count" field.
	DefaultRequestedOutputCount int
	// DefaultImageSize holds the default value on creation for the "image_size" field.
	DefaultImageSize string
	// ImageSizeValidator is a validator for the "image_size" field. It is called by the builders before save.
	ImageSizeValidator func(string) error
	// DefaultAspectRatio holds the default value on creation for the "aspect_ratio" field.
	DefaultAspectRatio string
	// AspectRatioValidator is a validator for the "aspect_ratio" field. It is called by the builders before save.
	AspectRatioValidator func(string) error
	// DefaultResponseMimeType holds the default value on creation for the "response_mime_type" field.
	DefaultResponseMimeType string
	// ResponseMimeTypeValidator is a validator for the "response_mime_type" field. It is called by the builders before save.
	ResponseMimeTypeValidator func(string) error
	// PromptHashValidator is a validator for the "prompt_hash" field. It is called by the builders before save.
	PromptHashValidator func(string) error
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultBalanceHoldAmount holds the default value on creation for the "balance_hold_amount" field.
	DefaultBalanceHoldAmount float64
	// DefaultSubscriptionHoldAllocations holds the default value on creation for the "subscription_hold_allocations" field.
	DefaultSubscriptionHoldAllocations func() []domain.BillingAllocation
	// DefaultBaseUnitPrice holds the default value on creation for the "base_unit_price" field.
	DefaultBaseUnitPrice float64
	// DefaultSubscriptionRateMultiplier holds the default value on creation for the "subscription_rate_multiplier" field.
	DefaultSubscriptionRateMultiplier float64
	// DefaultBalanceRateMultiplier holds the default value on creation for the "balance_rate_multiplier" field.
	DefaultBalanceRateMultiplier float64
	// DefaultPlanGroupRateMultiplierEnabled holds the default value on creation for the "plan_group_rate_multiplier_enabled" field.
	DefaultPlanGroupRateMultiplierEnabled bool
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultReleaseTargetStatus holds the default value on creation for the "release_target_status" field.
	DefaultReleaseTargetStatus string
	// ReleaseTargetStatusValidator is a validator for the "release_target_status" field. It is called by the builders before save.
	ReleaseTargetStatusValidator func(string) error
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultAllowanceReserved holds the default value on creation for the "allowance_reserved" field.
	DefaultAllowanceReserved bool
	// DefaultProvisioningPhase holds the default value on creation for the "provisioning_phase" field.
	DefaultProvisioningPhase string
	// ProvisioningPhaseValidator is a validator for the "provisioning_phase" field. It is called by the builders before save.
	ProvisioningPhaseValidator func(string) error
	// DefaultSettlementAttemptCount holds the default value on creation for the "settlement_attempt_count" field.
	DefaultSettlementAttemptCount int
	// DefaultReleaseAttemptCount holds the default value on creation for the "release_attempt_count" field.
	DefaultReleaseAttemptCount int
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
)

// OrderOption defines the ordering options for the CreativeRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByWorkspaceID orders the results by the workspace_id field.
func ByWorkspaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByRequestedOutputCount orders the results by the requested_output_count field.
func ByRequestedOutputCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedOutputCount, opts...).ToFunc()
}

// ByImageSize orders the results by the image_size field.
func ByImageSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageSize, opts...).ToFunc()
}

// ByAspectRatio orders the results by the aspect_ratio field.
func ByAspectRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAspectRatio, opts...).ToFunc()
}

// ByResponseMimeType orders the results by the response_mime_type field.
func ByResponseMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseMimeType, opts...).ToFunc()
}

// ByPromptHash orders the results by the prompt_hash field.
func ByPromptHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptHash, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByBalanceHoldAmount orders the results by the balance_hold_amount field.
func ByBalanceHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceHoldAmount, opts...).ToFunc()
}

// ByBaseUnitPrice orders the results by the base_unit_price field.
func ByBaseUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseUnitPrice, opts...).ToFunc()
}

// BySubscriptionRateMultiplier orders the results by the subscription_rate_multiplier field.
func BySubscriptionRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionRateMultiplier, opts...).ToFunc()
}

// ByBalanceRateMultiplier orders the results by the balance_rate_multiplier field.
func ByBalanceRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceRateMultiplier, opts...).ToFunc()
}

// ByPlanGroupRateMultiplierEnabled orders the results by the plan_group_rate_multiplier_enabled field.
func ByPlanGroupRateMultiplierEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanGroupRateMultiplierEnabled, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByReleaseTargetStatus orders the results by the release_target_status field.
func ByReleaseTargetStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseTargetStatus, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByAllowanceReserved orders the results by the allowance_reserved field.
func ByAllowanceReserved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowanceReserved, opts...).ToFunc()
}

// ByProvisioningPhase orders the results by the provisioning_phase field.
func ByProvisioningPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvisioningPhase, opts...).ToFunc()
}

// ByProviderResultRecordedAt orders the results by the provider_result_recorded_at field.
func ByProviderResultRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderResultRecordedAt, opts...).ToFunc()
}

// BySettlementAttemptCount orders the results by the settlement_attempt_count field.
func BySettlementAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementAttemptCount, opts...).ToFunc()
}

// ByReleaseAttemptCount orders the results by the release_attempt_count field.
func ByReleaseAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseAttemptCount, opts...).ToFunc()
}

// ByNextReconcileAt orders the results by the next_reconcile_at field.
func ByNextReconcileAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextReconcileAt, opts...).ToFunc()
}

// ByLastReconcileError orders the results by the last_reconcile_error field.
func ByLastReconcileError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReconcileError, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCancelledAt orders the results by the cancelled_at field.
func ByCancelledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelledAt, opts...).ToFunc()
}
