// Code generated by ent, DO NOT EDIT.

package apikeycompositegroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldGroupID, v))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldPrefix, v))
}

// NormalizedPrefix applies equality check predicate on the "normalized_prefix" field. It's identical to NormalizedPrefixEQ.
func NormalizedPrefix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldNormalizedPrefix, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldContainsFold(FieldPrefix, v))
}

// NormalizedPrefixEQ applies the EQ predicate on the "normalized_prefix" field.
func NormalizedPrefixEQ(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldNormalizedPrefix, v))
}

// NormalizedPrefixNEQ applies the NEQ predicate on the "normalized_prefix" field.
func NormalizedPrefixNEQ(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldNormalizedPrefix, v))
}

// NormalizedPrefixIn applies the In predicate on the "normalized_prefix" field.
func NormalizedPrefixIn(vs ...string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldNormalizedPrefix, vs...))
}

// NormalizedPrefixNotIn applies the NotIn predicate on the "normalized_prefix" field.
func NormalizedPrefixNotIn(vs ...string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldNormalizedPrefix, vs...))
}

// NormalizedPrefixGT applies the GT predicate on the "normalized_prefix" field.
func NormalizedPrefixGT(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldNormalizedPrefix, v))
}

// NormalizedPrefixGTE applies the GTE predicate on the "normalized_prefix" field.
func NormalizedPrefixGTE(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldNormalizedPrefix, v))
}

// NormalizedPrefixLT applies the LT predicate on the "normalized_prefix" field.
func NormalizedPrefixLT(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldNormalizedPrefix, v))
}

// NormalizedPrefixLTE applies the LTE predicate on the "normalized_prefix" field.
func NormalizedPrefixLTE(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldNormalizedPrefix, v))
}

// NormalizedPrefixContains applies the Contains predicate on the "normalized_prefix" field.
func NormalizedPrefixContains(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldContains(FieldNormalizedPrefix, v))
}

// NormalizedPrefixHasPrefix applies the HasPrefix predicate on the "normalized_prefix" field.
func NormalizedPrefixHasPrefix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldHasPrefix(FieldNormalizedPrefix, v))
}

// NormalizedPrefixHasSuffix applies the HasSuffix predicate on the "normalized_prefix" field.
func NormalizedPrefixHasSuffix(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldHasSuffix(FieldNormalizedPrefix, v))
}

// NormalizedPrefixEqualFold applies the EqualFold predicate on the "normalized_prefix" field.
func NormalizedPrefixEqualFold(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEqualFold(FieldNormalizedPrefix, v))
}

// NormalizedPrefixContainsFold applies the ContainsFold predicate on the "normalized_prefix" field.
func NormalizedPrefixContainsFold(v string) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldContainsFold(FieldNormalizedPrefix, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.FieldLTE(FieldSortOrder, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyCompositeGroup) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyCompositeGroup) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyCompositeGroup) predicate.APIKeyCompositeGroup {
	return predicate.APIKeyCompositeGroup(sql.NotPredicates(p))
}
