// Code generated by ent, DO NOT EDIT.

package tlsfingerprintrouter

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tlsfingerprintrouter type in the database.
	Label = "tls_fingerprint_router"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldChatgptOauthTokenUserAgent holds the string denoting the chatgpt_oauth_token_user_agent field in the database.
	FieldChatgptOauthTokenUserAgent = "chatgpt_oauth_token_user_agent"
	// FieldChatgptOauthTokenTLSFingerprintProfileID holds the string denoting the chatgpt_oauth_token_tls_fingerprint_profile_id field in the database.
	FieldChatgptOauthTokenTLSFingerprintProfileID = "chatgpt_oauth_token_tls_fingerprint_profile_id"
	// FieldCodexInviteResetUserAgent holds the string denoting the codex_invite_reset_user_agent field in the database.
	FieldCodexInviteResetUserAgent = "codex_invite_reset_user_agent"
	// FieldCodexInviteResetTLSFingerprintProfileID holds the string denoting the codex_invite_reset_tls_fingerprint_profile_id field in the database.
	FieldCodexInviteResetTLSFingerprintProfileID = "codex_invite_reset_tls_fingerprint_profile_id"
	// FieldRules holds the string denoting the rules field in the database.
	FieldRules = "rules"
	// Table holds the table name of the tlsfingerprintrouter in the database.
	Table = "tls_fingerprint_routers"
)

// Columns holds all SQL columns for tlsfingerprintrouter fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldDescription,
	FieldEnabled,
	FieldChatgptOauthTokenUserAgent,
	FieldChatgptOauthTokenTLSFingerprintProfileID,
	FieldCodexInviteResetUserAgent,
	FieldCodexInviteResetTLSFingerprintProfileID,
	FieldRules,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultChatgptOauthTokenUserAgent holds the default value on creation for the "chatgpt_oauth_token_user_agent" field.
	DefaultChatgptOauthTokenUserAgent string
	// ChatgptOauthTokenUserAgentValidator is a validator for the "chatgpt_oauth_token_user_agent" field. It is called by the builders before save.
	ChatgptOauthTokenUserAgentValidator func(string) error
	// DefaultCodexInviteResetUserAgent holds the default value on creation for the "codex_invite_reset_user_agent" field.
	DefaultCodexInviteResetUserAgent string
	// CodexInviteResetUserAgentValidator is a validator for the "codex_invite_reset_user_agent" field. It is called by the builders before save.
	CodexInviteResetUserAgentValidator func(string) error
)

// OrderOption defines the ordering options for the TLSFingerprintRouter queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByChatgptOauthTokenUserAgent orders the results by the chatgpt_oauth_token_user_agent field.
func ByChatgptOauthTokenUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatgptOauthTokenUserAgent, opts...).ToFunc()
}

// ByChatgptOauthTokenTLSFingerprintProfileID orders the results by the chatgpt_oauth_token_tls_fingerprint_profile_id field.
func ByChatgptOauthTokenTLSFingerprintProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatgptOauthTokenTLSFingerprintProfileID, opts...).ToFunc()
}

// ByCodexInviteResetUserAgent orders the results by the codex_invite_reset_user_agent field.
func ByCodexInviteResetUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexInviteResetUserAgent, opts...).ToFunc()
}

// ByCodexInviteResetTLSFingerprintProfileID orders the results by the codex_invite_reset_tls_fingerprint_profile_id field.
func ByCodexInviteResetTLSFingerprintProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexInviteResetTLSFingerprintProfileID, opts...).ToFunc()
}
