// Code generated by ent, DO NOT EDIT.

package tlsfingerprintrouter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldDescription, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldEnabled, v))
}

// ChatgptOauthTokenUserAgent applies equality check predicate on the "chatgpt_oauth_token_user_agent" field. It's identical to ChatgptOauthTokenUserAgentEQ.
func ChatgptOauthTokenUserAgent(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenTLSFingerprintProfileID applies equality check predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field. It's identical to ChatgptOauthTokenTLSFingerprintProfileIDEQ.
func ChatgptOauthTokenTLSFingerprintProfileID(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// CodexInviteResetUserAgent applies equality check predicate on the "codex_invite_reset_user_agent" field. It's identical to CodexInviteResetUserAgentEQ.
func CodexInviteResetUserAgent(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetTLSFingerprintProfileID applies equality check predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field. It's identical to CodexInviteResetTLSFingerprintProfileIDEQ.
func CodexInviteResetTLSFingerprintProfileID(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContainsFold(FieldDescription, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldEnabled, v))
}

// ChatgptOauthTokenUserAgentEQ applies the EQ predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentNEQ applies the NEQ predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentNEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentIn applies the In predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldChatgptOauthTokenUserAgent, vs...))
}

// ChatgptOauthTokenUserAgentNotIn applies the NotIn predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentNotIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldChatgptOauthTokenUserAgent, vs...))
}

// ChatgptOauthTokenUserAgentGT applies the GT predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentGT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentGTE applies the GTE predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentGTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentLT applies the LT predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentLT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentLTE applies the LTE predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentLTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentContains applies the Contains predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentContains(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContains(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentHasPrefix applies the HasPrefix predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentHasPrefix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasPrefix(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentHasSuffix applies the HasSuffix predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentHasSuffix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasSuffix(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentEqualFold applies the EqualFold predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentEqualFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEqualFold(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenUserAgentContainsFold applies the ContainsFold predicate on the "chatgpt_oauth_token_user_agent" field.
func ChatgptOauthTokenUserAgentContainsFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContainsFold(FieldChatgptOauthTokenUserAgent, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDEQ applies the EQ predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDEQ(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDNEQ applies the NEQ predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDNEQ(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDIn applies the In predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDIn(vs ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldChatgptOauthTokenTLSFingerprintProfileID, vs...))
}

// ChatgptOauthTokenTLSFingerprintProfileIDNotIn applies the NotIn predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDNotIn(vs ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldChatgptOauthTokenTLSFingerprintProfileID, vs...))
}

// ChatgptOauthTokenTLSFingerprintProfileIDGT applies the GT predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDGT(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDGTE applies the GTE predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDGTE(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDLT applies the LT predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDLT(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDLTE applies the LTE predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDLTE(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldChatgptOauthTokenTLSFingerprintProfileID, v))
}

// ChatgptOauthTokenTLSFingerprintProfileIDIsNil applies the IsNil predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDIsNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIsNull(FieldChatgptOauthTokenTLSFingerprintProfileID))
}

// ChatgptOauthTokenTLSFingerprintProfileIDNotNil applies the NotNil predicate on the "chatgpt_oauth_token_tls_fingerprint_profile_id" field.
func ChatgptOauthTokenTLSFingerprintProfileIDNotNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotNull(FieldChatgptOauthTokenTLSFingerprintProfileID))
}

// CodexInviteResetUserAgentEQ applies the EQ predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentNEQ applies the NEQ predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentNEQ(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentIn applies the In predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldCodexInviteResetUserAgent, vs...))
}

// CodexInviteResetUserAgentNotIn applies the NotIn predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentNotIn(vs ...string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldCodexInviteResetUserAgent, vs...))
}

// CodexInviteResetUserAgentGT applies the GT predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentGT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentGTE applies the GTE predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentGTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentLT applies the LT predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentLT(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentLTE applies the LTE predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentLTE(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentContains applies the Contains predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentContains(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContains(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentHasPrefix applies the HasPrefix predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentHasPrefix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasPrefix(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentHasSuffix applies the HasSuffix predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentHasSuffix(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldHasSuffix(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentEqualFold applies the EqualFold predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentEqualFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEqualFold(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetUserAgentContainsFold applies the ContainsFold predicate on the "codex_invite_reset_user_agent" field.
func CodexInviteResetUserAgentContainsFold(v string) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldContainsFold(FieldCodexInviteResetUserAgent, v))
}

// CodexInviteResetTLSFingerprintProfileIDEQ applies the EQ predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDEQ(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldEQ(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDNEQ applies the NEQ predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDNEQ(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNEQ(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDIn applies the In predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDIn(vs ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIn(FieldCodexInviteResetTLSFingerprintProfileID, vs...))
}

// CodexInviteResetTLSFingerprintProfileIDNotIn applies the NotIn predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDNotIn(vs ...int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotIn(FieldCodexInviteResetTLSFingerprintProfileID, vs...))
}

// CodexInviteResetTLSFingerprintProfileIDGT applies the GT predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDGT(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGT(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDGTE applies the GTE predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDGTE(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldGTE(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDLT applies the LT predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDLT(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLT(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDLTE applies the LTE predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDLTE(v int64) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldLTE(FieldCodexInviteResetTLSFingerprintProfileID, v))
}

// CodexInviteResetTLSFingerprintProfileIDIsNil applies the IsNil predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDIsNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIsNull(FieldCodexInviteResetTLSFingerprintProfileID))
}

// CodexInviteResetTLSFingerprintProfileIDNotNil applies the NotNil predicate on the "codex_invite_reset_tls_fingerprint_profile_id" field.
func CodexInviteResetTLSFingerprintProfileIDNotNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotNull(FieldCodexInviteResetTLSFingerprintProfileID))
}

// RulesIsNil applies the IsNil predicate on the "rules" field.
func RulesIsNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldIsNull(FieldRules))
}

// RulesNotNil applies the NotNil predicate on the "rules" field.
func RulesNotNil() predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.FieldNotNull(FieldRules))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TLSFingerprintRouter) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TLSFingerprintRouter) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TLSFingerprintRouter) predicate.TLSFingerprintRouter {
	return predicate.TLSFingerprintRouter(sql.NotPredicates(p))
}
