// Code generated by ent, DO NOT EDIT.

package creativerunoutput

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the creativerunoutput type in the database.
	Label = "creative_run_output"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRunID holds the string denoting the run_id field in the database.
	FieldRunID = "run_id"
	// FieldOutputIndex holds the string denoting the output_index field in the database.
	FieldOutputIndex = "output_index"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldByteSize holds the string denoting the byte_size field in the database.
	FieldByteSize = "byte_size"
	// FieldTransientExpiresAt holds the string denoting the transient_expires_at field in the database.
	FieldTransientExpiresAt = "transient_expires_at"
	// FieldAckedAt holds the string denoting the acked_at field in the database.
	FieldAckedAt = "acked_at"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// Table holds the table name of the creativerunoutput in the database.
	Table = "creative_run_outputs"
)

// Columns holds all SQL columns for creativerunoutput fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRunID,
	FieldOutputIndex,
	FieldStatus,
	FieldMimeType,
	FieldByteSize,
	FieldTransientExpiresAt,
	FieldAckedAt,
	FieldErrorCode,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	RunIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	MimeTypeValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
)

// OrderOption defines the ordering options for the CreativeRunOutput queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRunID orders the results by the run_id field.
func ByRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRunID, opts...).ToFunc()
}

// ByOutputIndex orders the results by the output_index field.
func ByOutputIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputIndex, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMimeType orders the results by the mime_type field.
func ByMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMimeType, opts...).ToFunc()
}

// ByByteSize orders the results by the byte_size field.
func ByByteSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldByteSize, opts...).ToFunc()
}

// ByTransientExpiresAt orders the results by the transient_expires_at field.
func ByTransientExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransientExpiresAt, opts...).ToFunc()
}

// ByAckedAt orders the results by the acked_at field.
func ByAckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAckedAt, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}
