// Code generated by ent, DO NOT EDIT.

package creativerunoutput

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/TokenFlux/TokenRouter/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldUpdatedAt, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldRunID, v))
}

// OutputIndex applies equality check predicate on the "output_index" field. It's identical to OutputIndexEQ.
func OutputIndex(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldOutputIndex, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldStatus, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldMimeType, v))
}

// ByteSize applies equality check predicate on the "byte_size" field. It's identical to ByteSizeEQ.
func ByteSize(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldByteSize, v))
}

// TransientExpiresAt applies equality check predicate on the "transient_expires_at" field. It's identical to TransientExpiresAtEQ.
func TransientExpiresAt(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldTransientExpiresAt, v))
}

// AckedAt applies equality check predicate on the "acked_at" field. It's identical to AckedAtEQ.
func AckedAt(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldAckedAt, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldUpdatedAt, v))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldRunID, v))
}

// RunIDContains applies the Contains predicate on the "run_id" field.
func RunIDContains(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContains(FieldRunID, v))
}

// RunIDHasPrefix applies the HasPrefix predicate on the "run_id" field.
func RunIDHasPrefix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasPrefix(FieldRunID, v))
}

// RunIDHasSuffix applies the HasSuffix predicate on the "run_id" field.
func RunIDHasSuffix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasSuffix(FieldRunID, v))
}

// RunIDEqualFold applies the EqualFold predicate on the "run_id" field.
func RunIDEqualFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEqualFold(FieldRunID, v))
}

// RunIDContainsFold applies the ContainsFold predicate on the "run_id" field.
func RunIDContainsFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContainsFold(FieldRunID, v))
}

// OutputIndexEQ applies the EQ predicate on the "output_index" field.
func OutputIndexEQ(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldOutputIndex, v))
}

// OutputIndexNEQ applies the NEQ predicate on the "output_index" field.
func OutputIndexNEQ(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldOutputIndex, v))
}

// OutputIndexIn applies the In predicate on the "output_index" field.
func OutputIndexIn(vs ...int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldOutputIndex, vs...))
}

// OutputIndexNotIn applies the NotIn predicate on the "output_index" field.
func OutputIndexNotIn(vs ...int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldOutputIndex, vs...))
}

// OutputIndexGT applies the GT predicate on the "output_index" field.
func OutputIndexGT(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldOutputIndex, v))
}

// OutputIndexGTE applies the GTE predicate on the "output_index" field.
func OutputIndexGTE(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldOutputIndex, v))
}

// OutputIndexLT applies the LT predicate on the "output_index" field.
func OutputIndexLT(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldOutputIndex, v))
}

// OutputIndexLTE applies the LTE predicate on the "output_index" field.
func OutputIndexLTE(v int) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldOutputIndex, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContainsFold(FieldStatus, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContainsFold(FieldMimeType, v))
}

// ByteSizeEQ applies the EQ predicate on the "byte_size" field.
func ByteSizeEQ(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldByteSize, v))
}

// ByteSizeNEQ applies the NEQ predicate on the "byte_size" field.
func ByteSizeNEQ(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldByteSize, v))
}

// ByteSizeIn applies the In predicate on the "byte_size" field.
func ByteSizeIn(vs ...int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldByteSize, vs...))
}

// ByteSizeNotIn applies the NotIn predicate on the "byte_size" field.
func ByteSizeNotIn(vs ...int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldByteSize, vs...))
}

// ByteSizeGT applies the GT predicate on the "byte_size" field.
func ByteSizeGT(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldByteSize, v))
}

// ByteSizeGTE applies the GTE predicate on the "byte_size" field.
func ByteSizeGTE(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldByteSize, v))
}

// ByteSizeLT applies the LT predicate on the "byte_size" field.
func ByteSizeLT(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldByteSize, v))
}

// ByteSizeLTE applies the LTE predicate on the "byte_size" field.
func ByteSizeLTE(v int64) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldByteSize, v))
}

// ByteSizeIsNil applies the IsNil predicate on the "byte_size" field.
func ByteSizeIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldByteSize))
}

// ByteSizeNotNil applies the NotNil predicate on the "byte_size" field.
func ByteSizeNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldByteSize))
}

// TransientExpiresAtEQ applies the EQ predicate on the "transient_expires_at" field.
func TransientExpiresAtEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldTransientExpiresAt, v))
}

// TransientExpiresAtNEQ applies the NEQ predicate on the "transient_expires_at" field.
func TransientExpiresAtNEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldTransientExpiresAt, v))
}

// TransientExpiresAtIn applies the In predicate on the "transient_expires_at" field.
func TransientExpiresAtIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldTransientExpiresAt, vs...))
}

// TransientExpiresAtNotIn applies the NotIn predicate on the "transient_expires_at" field.
func TransientExpiresAtNotIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldTransientExpiresAt, vs...))
}

// TransientExpiresAtGT applies the GT predicate on the "transient_expires_at" field.
func TransientExpiresAtGT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldTransientExpiresAt, v))
}

// TransientExpiresAtGTE applies the GTE predicate on the "transient_expires_at" field.
func TransientExpiresAtGTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldTransientExpiresAt, v))
}

// TransientExpiresAtLT applies the LT predicate on the "transient_expires_at" field.
func TransientExpiresAtLT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldTransientExpiresAt, v))
}

// TransientExpiresAtLTE applies the LTE predicate on the "transient_expires_at" field.
func TransientExpiresAtLTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldTransientExpiresAt, v))
}

// TransientExpiresAtIsNil applies the IsNil predicate on the "transient_expires_at" field.
func TransientExpiresAtIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldTransientExpiresAt))
}

// TransientExpiresAtNotNil applies the NotNil predicate on the "transient_expires_at" field.
func TransientExpiresAtNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldTransientExpiresAt))
}

// AckedAtEQ applies the EQ predicate on the "acked_at" field.
func AckedAtEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldAckedAt, v))
}

// AckedAtNEQ applies the NEQ predicate on the "acked_at" field.
func AckedAtNEQ(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldAckedAt, v))
}

// AckedAtIn applies the In predicate on the "acked_at" field.
func AckedAtIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldAckedAt, vs...))
}

// AckedAtNotIn applies the NotIn predicate on the "acked_at" field.
func AckedAtNotIn(vs ...time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldAckedAt, vs...))
}

// AckedAtGT applies the GT predicate on the "acked_at" field.
func AckedAtGT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldAckedAt, v))
}

// AckedAtGTE applies the GTE predicate on the "acked_at" field.
func AckedAtGTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldAckedAt, v))
}

// AckedAtLT applies the LT predicate on the "acked_at" field.
func AckedAtLT(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldAckedAt, v))
}

// AckedAtLTE applies the LTE predicate on the "acked_at" field.
func AckedAtLTE(v time.Time) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldAckedAt, v))
}

// AckedAtIsNil applies the IsNil predicate on the "acked_at" field.
func AckedAtIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldAckedAt))
}

// AckedAtNotNil applies the NotNil predicate on the "acked_at" field.
func AckedAtNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldAckedAt))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.FieldContainsFold(FieldErrorMessage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreativeRunOutput) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreativeRunOutput) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreativeRunOutput) predicate.CreativeRunOutput {
	return predicate.CreativeRunOutput(sql.NotPredicates(p))
}
